#variables using uppercase will be handled by the "env" file provided at runtime to docker-compose (during the deployment of the application)
services:
  db:
    image: mariadb:12.0
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: rodano
      MARIADB_AUTO_UPGRADE: true
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 10s
      retries: 5
      interval: 5s
      timeout: 30s
    restart: on-failure

  plugins-compiler:
    image: ghcr.io/rodano/plugins-compiler:${TAG}
    volumes:
      #access to the study package, to compile the plugins
      - type: bind
        source: ${STUDY_PATH}/backend
        target: /app
        read_only: false
    working_dir: /app

#this service can be removed if an external SMTP server is used
  smtp:
    image: ixdotai/smtp
    restart: on-failure

  backend:
    image: ghcr.io/rodano/backend:${TAG}
    depends_on:
      plugins-compiler:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      smtp:
        condition: service_started
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      #access to the study package, to get the configuration
      - type: bind
        source: ${STUDY_PATH}
        target: /app/study
        read_only: true
      #access to the study package, to get the plugins
      - type: bind
        source: ${STUDY_PATH}/backend/target/classes
        target: /app/plugins
        read_only: true
     #access to the volume containing resources uploaded by users
      - type: volume
        source: user_content
        target: /app/user_content
        read_only: false
    environment:
      JVM_OPTS: -Xmx512M -XX:+ExitOnOutOfMemoryError
      spring.profiles.active: api,study
      rodano.config: /app/study/config.json
      rodano.environment: VAL
      rodano.database.host: db
      rodano.database.port: 3306
      rodano.database.name: rodano
      rodano.path.data: /app/user_content
      spring.datasource.username: root
      spring.datasource.password: root
      #provide the following spring.mail.xxx properties if you use an external SMTP server
      spring.mail.host: ${SMTP_HOST:-smtp}
      spring.mail.port: ${SMTP_PORT:-25}
      spring.mail.username: ${SMTP_USERNAME:-anonymous}
      spring.mail.password: ${SMTP_PASSWORD:-unused-but-required}
      logging.level.ch.rodano.core: INFO
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s http://localhost:8080/administration/is-online | grep -q 'study is up'"
        ]
      start_period: 30s
      retries: 5
      interval: 10s
      timeout: 10s
    restart: on-failure

  frontend:
    image: ghcr.io/rodano/frontend:${TAG}
    build:
      context: frontends
      dockerfile: Dockerfile
    depends_on:
      - backend
      - manager
    ports:
      - "0.0.0.0:7586:7586"
    volumes:
      #access to the study package, to get the static files
      - type: bind
        source: ${STUDY_PATH}
        target: /app/study
        read_only: true
    restart: on-failure

  manager:
    image: ghcr.io/rodano/manager:${TAG}
    build:
      context: manager
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      #access to the user content to back it up and to restore it
      - user_content:/user_content
      - backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: rodano
      BASE_URL_PATH: /manager/
      MAGIC_TOKEN: ${MANAGER_MAGIC_TOKEN}
      USER_CONTENT: /user_content
      BACKUPS_PATH: /backups
      BACKUP_CRON_EXPRESSION: "0 3 * * *"
    restart: on-failure

volumes:
  #database volume, to persist the database content
  database:
  #user uploaded content, such as CRF files and resources
  user_content:
  #place where to store backups
  #can be mapped to local folder or to a network share
  backups:
  #  driver_opts:
  #    type: cifs
  #    o: "username=${BACKUP_USERNAME},password=${BACKUP_PASSWORD},domain=MS,noperm"
  #    device: "//${BACKUP_HOST}/backups/"
