/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.Chart.ChartPath;
import ch.rodano.core.model.jooq.tables.Dataset.DatasetPath;
import ch.rodano.core.model.jooq.tables.EventModelDatasetModel.EventModelDatasetModelPath;
import ch.rodano.core.model.jooq.tables.Field.FieldPath;
import ch.rodano.core.model.jooq.tables.FieldAudit.FieldAuditPath;
import ch.rodano.core.model.jooq.tables.FieldModel.FieldModelPath;
import ch.rodano.core.model.jooq.tables.FormLayout.FormLayoutPath;
import ch.rodano.core.model.jooq.tables.FormLayoutCell.FormLayoutCellPath;
import ch.rodano.core.model.jooq.tables.ProfileDatasetModelRights.ProfileDatasetModelRightsPath;
import ch.rodano.core.model.jooq.tables.Project.ProjectPath;
import ch.rodano.core.model.jooq.tables.Report.ReportPath;
import ch.rodano.core.model.jooq.tables.ScopeModelDatasetModel.ScopeModelDatasetModelPath;
import ch.rodano.core.model.jooq.tables.TimelineGraphSection.TimelineGraphSectionPath;
import ch.rodano.core.model.jooq.tables.records.DatasetModelRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DatasetModel extends TableImpl<DatasetModelRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>dataset_model</code>
	 */
	public static final DatasetModel DATASET_MODEL = new DatasetModel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DatasetModelRecord> getRecordType() {
		return DatasetModelRecord.class;
	}

	/**
	 * The column <code>dataset_model.dataset_model_id</code>.
	 */
	public final TableField<DatasetModelRecord, UUID> DATASET_MODEL_ID = createField(DSL.name("dataset_model_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>dataset_model.project_id</code>.
	 */
	public final TableField<DatasetModelRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>dataset_model.code</code>.
	 */
	public final TableField<DatasetModelRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>dataset_model.shortname</code>.
	 */
	public final TableField<DatasetModelRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>dataset_model.longname</code>.
	 */
	public final TableField<DatasetModelRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>dataset_model.description</code>.
	 */
	public final TableField<DatasetModelRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>dataset_model.multiple</code>.
	 */
	public final TableField<DatasetModelRecord, Boolean> MULTIPLE = createField(DSL.name("multiple"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>dataset_model.master</code>.
	 */
	public final TableField<DatasetModelRecord, Boolean> MASTER = createField(DSL.name("master"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>dataset_model.exportable</code>.
	 */
	public final TableField<DatasetModelRecord, Boolean> EXPORTABLE = createField(DSL.name("exportable"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>dataset_model.export_order</code>.
	 */
	public final TableField<DatasetModelRecord, Integer> EXPORT_ORDER = createField(DSL.name("export_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>dataset_model.family</code>.
	 */
	public final TableField<DatasetModelRecord, String> FAMILY = createField(DSL.name("family"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>dataset_model.collapsed_label_pattern</code>.
	 */
	public final TableField<DatasetModelRecord, String> COLLAPSED_LABEL_PATTERN = createField(DSL.name("collapsed_label_pattern"), SQLDataType.VARCHAR(512).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>dataset_model.expanded_label_pattern</code>.
	 */
	public final TableField<DatasetModelRecord, String> EXPANDED_LABEL_PATTERN = createField(DSL.name("expanded_label_pattern"), SQLDataType.VARCHAR(512).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	private DatasetModel(Name alias, Table<DatasetModelRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private DatasetModel(Name alias, Table<DatasetModelRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>dataset_model</code> table reference
	 */
	public DatasetModel(String alias) {
		this(DSL.name(alias), DATASET_MODEL);
	}

	/**
	 * Create an aliased <code>dataset_model</code> table reference
	 */
	public DatasetModel(Name alias) {
		this(alias, DATASET_MODEL);
	}

	/**
	 * Create a <code>dataset_model</code> table reference
	 */
	public DatasetModel() {
		this(DSL.name("dataset_model"), null);
	}

	public <O extends Record> DatasetModel(Table<O> path, ForeignKey<O, DatasetModelRecord> childPath, InverseForeignKey<O, DatasetModelRecord> parentPath) {
		super(path, childPath, parentPath, DATASET_MODEL);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class DatasetModelPath extends DatasetModel implements Path<DatasetModelRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> DatasetModelPath(Table<O> path, ForeignKey<O, DatasetModelRecord> childPath, InverseForeignKey<O, DatasetModelRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private DatasetModelPath(Name alias, Table<DatasetModelRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public DatasetModelPath as(String alias) {
			return new DatasetModelPath(DSL.name(alias), this);
		}

		@Override
		public DatasetModelPath as(Name alias) {
			return new DatasetModelPath(alias, this);
		}

		@Override
		public DatasetModelPath as(Table<?> alias) {
			return new DatasetModelPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.DATASET_MODEL_IDX_DM_PROJECT_EXPORT, Indexes.DATASET_MODEL_IDX_DM_PROJECT_FAMILY);
	}

	@Override
	public UniqueKey<DatasetModelRecord> getPrimaryKey() {
		return Keys.KEY_DATASET_MODEL_PRIMARY;
	}

	@Override
	public List<UniqueKey<DatasetModelRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_DATASET_MODEL_UQ_DATASET_MODEL_CODE);
	}

	@Override
	public List<ForeignKey<DatasetModelRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_DATASET_MODEL_PROJECT);
	}

	private transient ProjectPath _project;

	/**
	 * Get the implicit join path to the <code>project</code> table.
	 */
	public ProjectPath project() {
		if (_project == null)
			_project = new ProjectPath(this, Keys.FK_DATASET_MODEL_PROJECT, null);

		return _project;
	}

	private transient ChartPath _chart;

	/**
	 * Get the implicit to-many join path to the <code>chart</code> table
	 */
	public ChartPath chart() {
		if (_chart == null)
			_chart = new ChartPath(this, null, Keys.FK_CHART_DATASET_MODEL.getInverseKey());

		return _chart;
	}

	private transient DatasetPath _dataset;

	/**
	 * Get the implicit to-many join path to the <code>dataset</code> table
	 */
	public DatasetPath dataset() {
		if (_dataset == null)
			_dataset = new DatasetPath(this, null, Keys.FK_DATASET_DATASET_MODEL.getInverseKey());

		return _dataset;
	}

	private transient EventModelDatasetModelPath _eventModelDatasetModel;

	/**
	 * Get the implicit to-many join path to the
	 * <code>event_model_dataset_model</code> table
	 */
	public EventModelDatasetModelPath eventModelDatasetModel() {
		if (_eventModelDatasetModel == null)
			_eventModelDatasetModel = new EventModelDatasetModelPath(this, null, Keys.FK_EVENT_MODEL_DATASET_MODEL_DATASET.getInverseKey());

		return _eventModelDatasetModel;
	}

	private transient FieldAuditPath _fieldAudit;

	/**
	 * Get the implicit to-many join path to the <code>field_audit</code> table
	 */
	public FieldAuditPath fieldAudit() {
		if (_fieldAudit == null)
			_fieldAudit = new FieldAuditPath(this, null, Keys.FK_FIELD_AUDIT_DATASET_MODEL_ID.getInverseKey());

		return _fieldAudit;
	}

	private transient FieldPath _field;

	/**
	 * Get the implicit to-many join path to the <code>field</code> table
	 */
	public FieldPath field() {
		if (_field == null)
			_field = new FieldPath(this, null, Keys.FK_FIELD_DATASET_MODEL_ID.getInverseKey());

		return _field;
	}

	private transient FieldModelPath _fieldModel;

	/**
	 * Get the implicit to-many join path to the <code>field_model</code> table
	 */
	public FieldModelPath fieldModel() {
		if (_fieldModel == null)
			_fieldModel = new FieldModelPath(this, null, Keys.FK_FIELD_MODEL_DATASET.getInverseKey());

		return _fieldModel;
	}

	private transient FormLayoutCellPath _formLayoutCell;

	/**
	 * Get the implicit to-many join path to the <code>form_layout_cell</code>
	 * table
	 */
	public FormLayoutCellPath formLayoutCell() {
		if (_formLayoutCell == null)
			_formLayoutCell = new FormLayoutCellPath(this, null, Keys.FK_FORM_LAYOUT_CELL_DATASET.getInverseKey());

		return _formLayoutCell;
	}

	private transient FormLayoutPath _formLayout;

	/**
	 * Get the implicit to-many join path to the <code>form_layout</code> table
	 */
	public FormLayoutPath formLayout() {
		if (_formLayout == null)
			_formLayout = new FormLayoutPath(this, null, Keys.FK_FORM_LAYOUT_DATASET.getInverseKey());

		return _formLayout;
	}

	private transient ProfileDatasetModelRightsPath _profileDatasetModelRights;

	/**
	 * Get the implicit to-many join path to the
	 * <code>profile_dataset_model_rights</code> table
	 */
	public ProfileDatasetModelRightsPath profileDatasetModelRights() {
		if (_profileDatasetModelRights == null)
			_profileDatasetModelRights = new ProfileDatasetModelRightsPath(this, null, Keys.FK_PROFILE_DATASET_MODEL_RIGHTS_DATASET_MODEL.getInverseKey());

		return _profileDatasetModelRights;
	}

	private transient ReportPath _report;

	/**
	 * Get the implicit to-many join path to the <code>report</code> table
	 */
	public ReportPath report() {
		if (_report == null)
			_report = new ReportPath(this, null, Keys.FK_REPORT_DATASET_MODEL.getInverseKey());

		return _report;
	}

	private transient ScopeModelDatasetModelPath _scopeModelDatasetModel;

	/**
	 * Get the implicit to-many join path to the
	 * <code>scope_model_dataset_model</code> table
	 */
	public ScopeModelDatasetModelPath scopeModelDatasetModel() {
		if (_scopeModelDatasetModel == null)
			_scopeModelDatasetModel = new ScopeModelDatasetModelPath(this, null, Keys.FK_SCOPE_MODEL_DATASET_MODEL_DATASET.getInverseKey());

		return _scopeModelDatasetModel;
	}

	private transient TimelineGraphSectionPath _timelineGraphSection;

	/**
	 * Get the implicit to-many join path to the
	 * <code>timeline_graph_section</code> table
	 */
	public TimelineGraphSectionPath timelineGraphSection() {
		if (_timelineGraphSection == null)
			_timelineGraphSection = new TimelineGraphSectionPath(this, null, Keys.FK_TIMELINE_GRAPH_SECTION_DATASET.getInverseKey());

		return _timelineGraphSection;
	}

	@Override
	public List<Check<DatasetModelRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public DatasetModel as(String alias) {
		return new DatasetModel(DSL.name(alias), this);
	}

	@Override
	public DatasetModel as(Name alias) {
		return new DatasetModel(alias, this);
	}

	@Override
	public DatasetModel as(Table<?> alias) {
		return new DatasetModel(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public DatasetModel rename(String name) {
		return new DatasetModel(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public DatasetModel rename(Name name) {
		return new DatasetModel(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public DatasetModel rename(Table<?> name) {
		return new DatasetModel(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel where(Condition condition) {
		return new DatasetModel(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public DatasetModel where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public DatasetModel where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public DatasetModel where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public DatasetModel where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public DatasetModel whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
