/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.EventModelDeadlineReferenceRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventModelDeadlineReference extends TableImpl<EventModelDeadlineReferenceRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>event_model_deadline_reference</code>
	 */
	public static final EventModelDeadlineReference EVENT_MODEL_DEADLINE_REFERENCE = new EventModelDeadlineReference();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventModelDeadlineReferenceRecord> getRecordType() {
		return EventModelDeadlineReferenceRecord.class;
	}

	/**
	 * The column <code>event_model_deadline_reference.project_id</code>.
	 */
	public final TableField<EventModelDeadlineReferenceRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>event_model_deadline_reference.event_model_id</code>.
	 */
	public final TableField<EventModelDeadlineReferenceRecord, UUID> EVENT_MODEL_ID = createField(DSL.name("event_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>event_model_deadline_reference.reference_event_model_id</code>.
	 */
	public final TableField<EventModelDeadlineReferenceRecord, UUID> REFERENCE_EVENT_MODEL_ID = createField(DSL.name("reference_event_model_id"), SQLDataType.UUID.nullable(false), this, "");

	private EventModelDeadlineReference(Name alias, Table<EventModelDeadlineReferenceRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private EventModelDeadlineReference(Name alias, Table<EventModelDeadlineReferenceRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>event_model_deadline_reference</code> table
	 * reference
	 */
	public EventModelDeadlineReference(String alias) {
		this(DSL.name(alias), EVENT_MODEL_DEADLINE_REFERENCE);
	}

	/**
	 * Create an aliased <code>event_model_deadline_reference</code> table
	 * reference
	 */
	public EventModelDeadlineReference(Name alias) {
		this(alias, EVENT_MODEL_DEADLINE_REFERENCE);
	}

	/**
	 * Create a <code>event_model_deadline_reference</code> table reference
	 */
	public EventModelDeadlineReference() {
		this(DSL.name("event_model_deadline_reference"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<EventModelDeadlineReferenceRecord> getPrimaryKey() {
		return Keys.KEY_EVENT_MODEL_DEADLINE_REFERENCE_PRIMARY;
	}

	@Override
	public EventModelDeadlineReference as(String alias) {
		return new EventModelDeadlineReference(DSL.name(alias), this);
	}

	@Override
	public EventModelDeadlineReference as(Name alias) {
		return new EventModelDeadlineReference(alias, this);
	}

	@Override
	public EventModelDeadlineReference as(Table<?> alias) {
		return new EventModelDeadlineReference(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDeadlineReference rename(String name) {
		return new EventModelDeadlineReference(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDeadlineReference rename(Name name) {
		return new EventModelDeadlineReference(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDeadlineReference rename(Table<?> name) {
		return new EventModelDeadlineReference(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference where(Condition condition) {
		return new EventModelDeadlineReference(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDeadlineReference where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDeadlineReference where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDeadlineReference where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDeadlineReference where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDeadlineReference whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
