/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.DatasetModel.DatasetModelPath;
import ch.rodano.core.model.jooq.tables.EventModel.EventModelPath;
import ch.rodano.core.model.jooq.tables.records.EventModelDatasetModelRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventModelDatasetModel extends TableImpl<EventModelDatasetModelRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>event_model_dataset_model</code>
	 */
	public static final EventModelDatasetModel EVENT_MODEL_DATASET_MODEL = new EventModelDatasetModel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EventModelDatasetModelRecord> getRecordType() {
		return EventModelDatasetModelRecord.class;
	}

	/**
	 * The column <code>event_model_dataset_model.project_id</code>.
	 */
	public final TableField<EventModelDatasetModelRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>event_model_dataset_model.event_model_id</code>.
	 */
	public final TableField<EventModelDatasetModelRecord, UUID> EVENT_MODEL_ID = createField(DSL.name("event_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>event_model_dataset_model.dataset_model_id</code>.
	 */
	public final TableField<EventModelDatasetModelRecord, UUID> DATASET_MODEL_ID = createField(DSL.name("dataset_model_id"), SQLDataType.UUID.nullable(false), this, "");

	private EventModelDatasetModel(Name alias, Table<EventModelDatasetModelRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private EventModelDatasetModel(Name alias, Table<EventModelDatasetModelRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>event_model_dataset_model</code> table reference
	 */
	public EventModelDatasetModel(String alias) {
		this(DSL.name(alias), EVENT_MODEL_DATASET_MODEL);
	}

	/**
	 * Create an aliased <code>event_model_dataset_model</code> table reference
	 */
	public EventModelDatasetModel(Name alias) {
		this(alias, EVENT_MODEL_DATASET_MODEL);
	}

	/**
	 * Create a <code>event_model_dataset_model</code> table reference
	 */
	public EventModelDatasetModel() {
		this(DSL.name("event_model_dataset_model"), null);
	}

	public <O extends Record> EventModelDatasetModel(Table<O> path, ForeignKey<O, EventModelDatasetModelRecord> childPath, InverseForeignKey<O, EventModelDatasetModelRecord> parentPath) {
		super(path, childPath, parentPath, EVENT_MODEL_DATASET_MODEL);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class EventModelDatasetModelPath extends EventModelDatasetModel implements Path<EventModelDatasetModelRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> EventModelDatasetModelPath(Table<O> path, ForeignKey<O, EventModelDatasetModelRecord> childPath, InverseForeignKey<O, EventModelDatasetModelRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private EventModelDatasetModelPath(Name alias, Table<EventModelDatasetModelRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public EventModelDatasetModelPath as(String alias) {
			return new EventModelDatasetModelPath(DSL.name(alias), this);
		}

		@Override
		public EventModelDatasetModelPath as(Name alias) {
			return new EventModelDatasetModelPath(alias, this);
		}

		@Override
		public EventModelDatasetModelPath as(Table<?> alias) {
			return new EventModelDatasetModelPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.EVENT_MODEL_DATASET_MODEL_IDX_EVENT_MODEL_DATASET_MODEL_DATASET, Indexes.EVENT_MODEL_DATASET_MODEL_IDX_EVENT_MODEL_DATASET_MODEL_EVENT);
	}

	@Override
	public UniqueKey<EventModelDatasetModelRecord> getPrimaryKey() {
		return Keys.KEY_EVENT_MODEL_DATASET_MODEL_PRIMARY;
	}

	@Override
	public List<ForeignKey<EventModelDatasetModelRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_EVENT_MODEL_DATASET_MODEL_DATASET, Keys.FK_EVENT_MODEL_DATASET_MODEL_EVENT);
	}

	private transient DatasetModelPath _datasetModel;

	/**
	 * Get the implicit join path to the <code>dataset_model</code> table.
	 */
	public DatasetModelPath datasetModel() {
		if (_datasetModel == null)
			_datasetModel = new DatasetModelPath(this, Keys.FK_EVENT_MODEL_DATASET_MODEL_DATASET, null);

		return _datasetModel;
	}

	private transient EventModelPath _eventModel;

	/**
	 * Get the implicit join path to the <code>event_model</code> table.
	 */
	public EventModelPath eventModel() {
		if (_eventModel == null)
			_eventModel = new EventModelPath(this, Keys.FK_EVENT_MODEL_DATASET_MODEL_EVENT, null);

		return _eventModel;
	}

	@Override
	public EventModelDatasetModel as(String alias) {
		return new EventModelDatasetModel(DSL.name(alias), this);
	}

	@Override
	public EventModelDatasetModel as(Name alias) {
		return new EventModelDatasetModel(alias, this);
	}

	@Override
	public EventModelDatasetModel as(Table<?> alias) {
		return new EventModelDatasetModel(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDatasetModel rename(String name) {
		return new EventModelDatasetModel(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDatasetModel rename(Name name) {
		return new EventModelDatasetModel(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public EventModelDatasetModel rename(Table<?> name) {
		return new EventModelDatasetModel(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel where(Condition condition) {
		return new EventModelDatasetModel(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDatasetModel where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDatasetModel where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDatasetModel where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public EventModelDatasetModel where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public EventModelDatasetModel whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
