/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.FormModelRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormModel extends TableImpl<FormModelRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>form_model</code>
	 */
	public static final FormModel FORM_MODEL = new FormModel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FormModelRecord> getRecordType() {
		return FormModelRecord.class;
	}

	/**
	 * The column <code>form_model.form_model_id</code>.
	 */
	public final TableField<FormModelRecord, UUID> FORM_MODEL_ID = createField(DSL.name("form_model_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>form_model.project_id</code>.
	 */
	public final TableField<FormModelRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>form_model.code</code>.
	 */
	public final TableField<FormModelRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>form_model.optional</code>.
	 */
	public final TableField<FormModelRecord, Boolean> OPTIONAL = createField(DSL.name("optional"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>form_model.shortname</code>.
	 */
	public final TableField<FormModelRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>form_model.longname</code>.
	 */
	public final TableField<FormModelRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>form_model.description</code>.
	 */
	public final TableField<FormModelRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>form_model.print_button_label</code>.
	 */
	public final TableField<FormModelRecord, String> PRINT_BUTTON_LABEL = createField(DSL.name("print_button_label"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	private FormModel(Name alias, Table<FormModelRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private FormModel(Name alias, Table<FormModelRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>form_model</code> table reference
	 */
	public FormModel(String alias) {
		this(DSL.name(alias), FORM_MODEL);
	}

	/**
	 * Create an aliased <code>form_model</code> table reference
	 */
	public FormModel(Name alias) {
		this(alias, FORM_MODEL);
	}

	/**
	 * Create a <code>form_model</code> table reference
	 */
	public FormModel() {
		this(DSL.name("form_model"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<FormModelRecord> getPrimaryKey() {
		return Keys.KEY_FORM_MODEL_PRIMARY;
	}

	@Override
	public List<UniqueKey<FormModelRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_FORM_MODEL_UQ_FORM_MODEL_CODE);
	}

	@Override
	public List<Check<FormModelRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("print_button_label"), "json_valid(`print_button_label`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public FormModel as(String alias) {
		return new FormModel(DSL.name(alias), this);
	}

	@Override
	public FormModel as(Name alias) {
		return new FormModel(alias, this);
	}

	@Override
	public FormModel as(Table<?> alias) {
		return new FormModel(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModel rename(String name) {
		return new FormModel(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModel rename(Name name) {
		return new FormModel(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModel rename(Table<?> name) {
		return new FormModel(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel where(Condition condition) {
		return new FormModel(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModel where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModel where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModel where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModel where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModel whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
