/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.FormModel.FormModelPath;
import ch.rodano.core.model.jooq.tables.Workflow.WorkflowPath;
import ch.rodano.core.model.jooq.tables.records.FormModelWorkflowRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormModelWorkflow extends TableImpl<FormModelWorkflowRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>form_model_workflow</code>
	 */
	public static final FormModelWorkflow FORM_MODEL_WORKFLOW = new FormModelWorkflow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FormModelWorkflowRecord> getRecordType() {
		return FormModelWorkflowRecord.class;
	}

	/**
	 * The column <code>form_model_workflow.project_id</code>.
	 */
	public final TableField<FormModelWorkflowRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>form_model_workflow.form_model_id</code>.
	 */
	public final TableField<FormModelWorkflowRecord, UUID> FORM_MODEL_ID = createField(DSL.name("form_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>form_model_workflow.workflow_id</code>.
	 */
	public final TableField<FormModelWorkflowRecord, UUID> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.UUID.nullable(false), this, "");

	private FormModelWorkflow(Name alias, Table<FormModelWorkflowRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private FormModelWorkflow(Name alias, Table<FormModelWorkflowRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>form_model_workflow</code> table reference
	 */
	public FormModelWorkflow(String alias) {
		this(DSL.name(alias), FORM_MODEL_WORKFLOW);
	}

	/**
	 * Create an aliased <code>form_model_workflow</code> table reference
	 */
	public FormModelWorkflow(Name alias) {
		this(alias, FORM_MODEL_WORKFLOW);
	}

	/**
	 * Create a <code>form_model_workflow</code> table reference
	 */
	public FormModelWorkflow() {
		this(DSL.name("form_model_workflow"), null);
	}

	public <O extends Record> FormModelWorkflow(Table<O> path, ForeignKey<O, FormModelWorkflowRecord> childPath, InverseForeignKey<O, FormModelWorkflowRecord> parentPath) {
		super(path, childPath, parentPath, FORM_MODEL_WORKFLOW);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class FormModelWorkflowPath extends FormModelWorkflow implements Path<FormModelWorkflowRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> FormModelWorkflowPath(Table<O> path, ForeignKey<O, FormModelWorkflowRecord> childPath, InverseForeignKey<O, FormModelWorkflowRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private FormModelWorkflowPath(Name alias, Table<FormModelWorkflowRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public FormModelWorkflowPath as(String alias) {
			return new FormModelWorkflowPath(DSL.name(alias), this);
		}

		@Override
		public FormModelWorkflowPath as(Name alias) {
			return new FormModelWorkflowPath(alias, this);
		}

		@Override
		public FormModelWorkflowPath as(Table<?> alias) {
			return new FormModelWorkflowPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<FormModelWorkflowRecord> getPrimaryKey() {
		return Keys.KEY_FORM_MODEL_WORKFLOW_PRIMARY;
	}

	@Override
	public List<ForeignKey<FormModelWorkflowRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_FORM_MODEL_WF_FORM, Keys.FK_FORM_MODEL_WF_WORKFLOW);
	}

	private transient FormModelPath _formModel;

	/**
	 * Get the implicit join path to the <code>form_model</code> table.
	 */
	public FormModelPath formModel() {
		if (_formModel == null)
			_formModel = new FormModelPath(this, Keys.FK_FORM_MODEL_WF_FORM, null);

		return _formModel;
	}

	private transient WorkflowPath _workflow;

	/**
	 * Get the implicit join path to the <code>workflow</code> table.
	 */
	public WorkflowPath workflow() {
		if (_workflow == null)
			_workflow = new WorkflowPath(this, Keys.FK_FORM_MODEL_WF_WORKFLOW, null);

		return _workflow;
	}

	@Override
	public FormModelWorkflow as(String alias) {
		return new FormModelWorkflow(DSL.name(alias), this);
	}

	@Override
	public FormModelWorkflow as(Name alias) {
		return new FormModelWorkflow(alias, this);
	}

	@Override
	public FormModelWorkflow as(Table<?> alias) {
		return new FormModelWorkflow(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModelWorkflow rename(String name) {
		return new FormModelWorkflow(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModelWorkflow rename(Name name) {
		return new FormModelWorkflow(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public FormModelWorkflow rename(Table<?> name) {
		return new FormModelWorkflow(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow where(Condition condition) {
		return new FormModelWorkflow(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModelWorkflow where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModelWorkflow where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModelWorkflow where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public FormModelWorkflow where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public FormModelWorkflow whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
