/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.Chart.ChartPath;
import ch.rodano.core.model.jooq.tables.MenuLayoutSectionWidget.MenuLayoutSectionWidgetPath;
import ch.rodano.core.model.jooq.tables.ResourceCategory.ResourceCategoryPath;
import ch.rodano.core.model.jooq.tables.ScopeModel.ScopeModelPath;
import ch.rodano.core.model.jooq.tables.WorkflowSummary.WorkflowSummaryPath;
import ch.rodano.core.model.jooq.tables.WorkflowWidget.WorkflowWidgetPath;
import ch.rodano.core.model.jooq.tables.records.MenuLayoutSectionWidgetParameterRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MenuLayoutSectionWidgetParameter extends TableImpl<MenuLayoutSectionWidgetParameterRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>menu_layout_section_widget_parameter</code>
	 */
	public static final MenuLayoutSectionWidgetParameter MENU_LAYOUT_SECTION_WIDGET_PARAMETER = new MenuLayoutSectionWidgetParameter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MenuLayoutSectionWidgetParameterRecord> getRecordType() {
		return MenuLayoutSectionWidgetParameterRecord.class;
	}

	/**
	 * The column <code>menu_layout_section_widget_parameter.project_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.menu_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>menu_layout_section_widget_parameter.menu_section_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> MENU_SECTION_ID = createField(DSL.name("menu_section_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.menu_widget_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> MENU_WIDGET_ID = createField(DSL.name("menu_widget_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.widget_order</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, Integer> WIDGET_ORDER = createField(DSL.name("widget_order"), SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.type</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.title</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.width</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, Integer> WIDTH = createField(DSL.name("width"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.scope_model_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> SCOPE_MODEL_ID = createField(DSL.name("scope_model_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column
	 * <code>menu_layout_section_widget_parameter.workflow_widget_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> WORKFLOW_WIDGET_ID = createField(DSL.name("workflow_widget_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column
	 * <code>menu_layout_section_widget_parameter.workflow_summary_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> WORKFLOW_SUMMARY_ID = createField(DSL.name("workflow_summary_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.chart_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> CHART_ID = createField(DSL.name("chart_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu_layout_section_widget_parameter.category_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetParameterRecord, UUID> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	private MenuLayoutSectionWidgetParameter(Name alias, Table<MenuLayoutSectionWidgetParameterRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private MenuLayoutSectionWidgetParameter(Name alias, Table<MenuLayoutSectionWidgetParameterRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>menu_layout_section_widget_parameter</code> table
	 * reference
	 */
	public MenuLayoutSectionWidgetParameter(String alias) {
		this(DSL.name(alias), MENU_LAYOUT_SECTION_WIDGET_PARAMETER);
	}

	/**
	 * Create an aliased <code>menu_layout_section_widget_parameter</code> table
	 * reference
	 */
	public MenuLayoutSectionWidgetParameter(Name alias) {
		this(alias, MENU_LAYOUT_SECTION_WIDGET_PARAMETER);
	}

	/**
	 * Create a <code>menu_layout_section_widget_parameter</code> table reference
	 */
	public MenuLayoutSectionWidgetParameter() {
		this(DSL.name("menu_layout_section_widget_parameter"), null);
	}

	public <O extends Record> MenuLayoutSectionWidgetParameter(Table<O> path, ForeignKey<O, MenuLayoutSectionWidgetParameterRecord> childPath, InverseForeignKey<O, MenuLayoutSectionWidgetParameterRecord> parentPath) {
		super(path, childPath, parentPath, MENU_LAYOUT_SECTION_WIDGET_PARAMETER);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class MenuLayoutSectionWidgetParameterPath extends MenuLayoutSectionWidgetParameter implements Path<MenuLayoutSectionWidgetParameterRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> MenuLayoutSectionWidgetParameterPath(Table<O> path, ForeignKey<O, MenuLayoutSectionWidgetParameterRecord> childPath, InverseForeignKey<O, MenuLayoutSectionWidgetParameterRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private MenuLayoutSectionWidgetParameterPath(Name alias, Table<MenuLayoutSectionWidgetParameterRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public MenuLayoutSectionWidgetParameterPath as(String alias) {
			return new MenuLayoutSectionWidgetParameterPath(DSL.name(alias), this);
		}

		@Override
		public MenuLayoutSectionWidgetParameterPath as(Name alias) {
			return new MenuLayoutSectionWidgetParameterPath(alias, this);
		}

		@Override
		public MenuLayoutSectionWidgetParameterPath as(Table<?> alias) {
			return new MenuLayoutSectionWidgetParameterPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<MenuLayoutSectionWidgetParameterRecord> getPrimaryKey() {
		return Keys.KEY_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_PRIMARY;
	}

	@Override
	public List<ForeignKey<MenuLayoutSectionWidgetParameterRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_CATEGORY, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_CHART, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_SCOPE, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WF_SUMMARY, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WF_WIDGET, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WIDGET);
	}

	private transient ResourceCategoryPath _resourceCategory;

	/**
	 * Get the implicit join path to the <code>resource_category</code> table.
	 */
	public ResourceCategoryPath resourceCategory() {
		if (_resourceCategory == null)
			_resourceCategory = new ResourceCategoryPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_CATEGORY, null);

		return _resourceCategory;
	}

	private transient ChartPath _chart;

	/**
	 * Get the implicit join path to the <code>chart</code> table.
	 */
	public ChartPath chart() {
		if (_chart == null)
			_chart = new ChartPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_CHART, null);

		return _chart;
	}

	private transient ScopeModelPath _scopeModel;

	/**
	 * Get the implicit join path to the <code>scope_model</code> table.
	 */
	public ScopeModelPath scopeModel() {
		if (_scopeModel == null)
			_scopeModel = new ScopeModelPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_SCOPE, null);

		return _scopeModel;
	}

	private transient WorkflowSummaryPath _workflowSummary;

	/**
	 * Get the implicit join path to the <code>workflow_summary</code> table.
	 */
	public WorkflowSummaryPath workflowSummary() {
		if (_workflowSummary == null)
			_workflowSummary = new WorkflowSummaryPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WF_SUMMARY, null);

		return _workflowSummary;
	}

	private transient WorkflowWidgetPath _workflowWidget;

	/**
	 * Get the implicit join path to the <code>workflow_widget</code> table.
	 */
	public WorkflowWidgetPath workflowWidget() {
		if (_workflowWidget == null)
			_workflowWidget = new WorkflowWidgetPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WF_WIDGET, null);

		return _workflowWidget;
	}

	private transient MenuLayoutSectionWidgetPath _menuLayoutSectionWidget;

	/**
	 * Get the implicit join path to the <code>menu_layout_section_widget</code>
	 * table.
	 */
	public MenuLayoutSectionWidgetPath menuLayoutSectionWidget() {
		if (_menuLayoutSectionWidget == null)
			_menuLayoutSectionWidget = new MenuLayoutSectionWidgetPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WIDGET, null);

		return _menuLayoutSectionWidget;
	}

	@Override
	public MenuLayoutSectionWidgetParameter as(String alias) {
		return new MenuLayoutSectionWidgetParameter(DSL.name(alias), this);
	}

	@Override
	public MenuLayoutSectionWidgetParameter as(Name alias) {
		return new MenuLayoutSectionWidgetParameter(alias, this);
	}

	@Override
	public MenuLayoutSectionWidgetParameter as(Table<?> alias) {
		return new MenuLayoutSectionWidgetParameter(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter rename(String name) {
		return new MenuLayoutSectionWidgetParameter(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter rename(Name name) {
		return new MenuLayoutSectionWidgetParameter(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter rename(Table<?> name) {
		return new MenuLayoutSectionWidgetParameter(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter where(Condition condition) {
		return new MenuLayoutSectionWidgetParameter(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidgetParameter where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidgetParameter where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidgetParameter where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidgetParameter where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidgetParameter whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
