/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.MenuRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Menu extends TableImpl<MenuRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>menu</code>
	 */
	public static final Menu MENU = new Menu();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MenuRecord> getRecordType() {
		return MenuRecord.class;
	}

	/**
	 * The column <code>menu.menu_id</code>.
	 */
	public final TableField<MenuRecord, UUID> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu.project_id</code>.
	 */
	public final TableField<MenuRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu.parent_menu_id</code>.
	 */
	public final TableField<MenuRecord, UUID> PARENT_MENU_ID = createField(DSL.name("parent_menu_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu.sort_order</code>.
	 */
	public final TableField<MenuRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>menu.code</code>.
	 */
	public final TableField<MenuRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>menu.order_by</code>.
	 */
	public final TableField<MenuRecord, Integer> ORDER_BY = createField(DSL.name("order_by"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>menu.shortname</code>.
	 */
	public final TableField<MenuRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu.longname</code>.
	 */
	public final TableField<MenuRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu.description</code>.
	 */
	public final TableField<MenuRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu.is_public</code>.
	 */
	public final TableField<MenuRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>menu.is_home_page</code>.
	 */
	public final TableField<MenuRecord, Boolean> IS_HOME_PAGE = createField(DSL.name("is_home_page"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	private Menu(Name alias, Table<MenuRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Menu(Name alias, Table<MenuRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>menu</code> table reference
	 */
	public Menu(String alias) {
		this(DSL.name(alias), MENU);
	}

	/**
	 * Create an aliased <code>menu</code> table reference
	 */
	public Menu(Name alias) {
		this(alias, MENU);
	}

	/**
	 * Create a <code>menu</code> table reference
	 */
	public Menu() {
		this(DSL.name("menu"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<MenuRecord> getPrimaryKey() {
		return Keys.KEY_MENU_PRIMARY;
	}

	@Override
	public List<UniqueKey<MenuRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_MENU_UQ_MENU_PROJECT_CODE);
	}

	@Override
	public List<Check<MenuRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public Menu as(String alias) {
		return new Menu(DSL.name(alias), this);
	}

	@Override
	public Menu as(Name alias) {
		return new Menu(alias, this);
	}

	@Override
	public Menu as(Table<?> alias) {
		return new Menu(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Menu rename(String name) {
		return new Menu(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Menu rename(Name name) {
		return new Menu(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Menu rename(Table<?> name) {
		return new Menu(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu where(Condition condition) {
		return new Menu(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Menu where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Menu where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Menu where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Menu where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Menu whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
