/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.Feature.FeaturePath;
import ch.rodano.core.model.jooq.tables.MenuLayoutSection.MenuLayoutSectionPath;
import ch.rodano.core.model.jooq.tables.MenuLayoutSectionWidgetParameter.MenuLayoutSectionWidgetParameterPath;
import ch.rodano.core.model.jooq.tables.records.MenuLayoutSectionWidgetRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MenuLayoutSectionWidget extends TableImpl<MenuLayoutSectionWidgetRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>menu_layout_section_widget</code>
	 */
	public static final MenuLayoutSectionWidget MENU_LAYOUT_SECTION_WIDGET = new MenuLayoutSectionWidget();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MenuLayoutSectionWidgetRecord> getRecordType() {
		return MenuLayoutSectionWidgetRecord.class;
	}

	/**
	 * The column <code>menu_layout_section_widget.menu_widget_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> MENU_WIDGET_ID = createField(DSL.name("menu_widget_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.project_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget.menu_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget.menu_section_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> MENU_SECTION_ID = createField(DSL.name("menu_section_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget.widget_order</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, Integer> WIDGET_ORDER = createField(DSL.name("widget_order"), SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget.type</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(64).nullable(false), this, "");

	/**
	 * The column <code>menu_layout_section_widget.width</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> WIDTH = createField(DSL.name("width"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.text_before</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> TEXT_BEFORE = createField(DSL.name("text_before"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.text_after</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> TEXT_AFTER = createField(DSL.name("text_after"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.required_feature_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> REQUIRED_FEATURE_ID = createField(DSL.name("required_feature_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.right_entity</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> RIGHT_ENTITY = createField(DSL.name("right_entity"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.right_value</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, String> RIGHT_VALUE = createField(DSL.name("right_value"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>menu_layout_section_widget.right_target_id</code>.
	 */
	public final TableField<MenuLayoutSectionWidgetRecord, UUID> RIGHT_TARGET_ID = createField(DSL.name("right_target_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	private MenuLayoutSectionWidget(Name alias, Table<MenuLayoutSectionWidgetRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private MenuLayoutSectionWidget(Name alias, Table<MenuLayoutSectionWidgetRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>menu_layout_section_widget</code> table reference
	 */
	public MenuLayoutSectionWidget(String alias) {
		this(DSL.name(alias), MENU_LAYOUT_SECTION_WIDGET);
	}

	/**
	 * Create an aliased <code>menu_layout_section_widget</code> table reference
	 */
	public MenuLayoutSectionWidget(Name alias) {
		this(alias, MENU_LAYOUT_SECTION_WIDGET);
	}

	/**
	 * Create a <code>menu_layout_section_widget</code> table reference
	 */
	public MenuLayoutSectionWidget() {
		this(DSL.name("menu_layout_section_widget"), null);
	}

	public <O extends Record> MenuLayoutSectionWidget(Table<O> path, ForeignKey<O, MenuLayoutSectionWidgetRecord> childPath, InverseForeignKey<O, MenuLayoutSectionWidgetRecord> parentPath) {
		super(path, childPath, parentPath, MENU_LAYOUT_SECTION_WIDGET);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class MenuLayoutSectionWidgetPath extends MenuLayoutSectionWidget implements Path<MenuLayoutSectionWidgetRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> MenuLayoutSectionWidgetPath(Table<O> path, ForeignKey<O, MenuLayoutSectionWidgetRecord> childPath, InverseForeignKey<O, MenuLayoutSectionWidgetRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private MenuLayoutSectionWidgetPath(Name alias, Table<MenuLayoutSectionWidgetRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public MenuLayoutSectionWidgetPath as(String alias) {
			return new MenuLayoutSectionWidgetPath(DSL.name(alias), this);
		}

		@Override
		public MenuLayoutSectionWidgetPath as(Name alias) {
			return new MenuLayoutSectionWidgetPath(alias, this);
		}

		@Override
		public MenuLayoutSectionWidgetPath as(Table<?> alias) {
			return new MenuLayoutSectionWidgetPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.MENU_LAYOUT_SECTION_WIDGET_IDX_MENU_WIDGET_FEATURE);
	}

	@Override
	public UniqueKey<MenuLayoutSectionWidgetRecord> getPrimaryKey() {
		return Keys.KEY_MENU_LAYOUT_SECTION_WIDGET_PRIMARY;
	}

	@Override
	public List<UniqueKey<MenuLayoutSectionWidgetRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_MENU_LAYOUT_SECTION_WIDGET_UQ_MENU_WIDGET_ORDER);
	}

	@Override
	public List<ForeignKey<MenuLayoutSectionWidgetRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_MENU_LAYOUT_SECTION_WIDGET_FEATURE, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_SECTION);
	}

	private transient FeaturePath _feature;

	/**
	 * Get the implicit join path to the <code>feature</code> table.
	 */
	public FeaturePath feature() {
		if (_feature == null)
			_feature = new FeaturePath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_FEATURE, null);

		return _feature;
	}

	private transient MenuLayoutSectionPath _menuLayoutSection;

	/**
	 * Get the implicit join path to the <code>menu_layout_section</code> table.
	 */
	public MenuLayoutSectionPath menuLayoutSection() {
		if (_menuLayoutSection == null)
			_menuLayoutSection = new MenuLayoutSectionPath(this, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_SECTION, null);

		return _menuLayoutSection;
	}

	private transient MenuLayoutSectionWidgetParameterPath _menuLayoutSectionWidgetParameter;

	/**
	 * Get the implicit to-many join path to the
	 * <code>menu_layout_section_widget_parameter</code> table
	 */
	public MenuLayoutSectionWidgetParameterPath menuLayoutSectionWidgetParameter() {
		if (_menuLayoutSectionWidgetParameter == null)
			_menuLayoutSectionWidgetParameter = new MenuLayoutSectionWidgetParameterPath(this, null, Keys.FK_MENU_LAYOUT_SECTION_WIDGET_PARAMETER_WIDGET.getInverseKey());

		return _menuLayoutSectionWidgetParameter;
	}

	@Override
	public MenuLayoutSectionWidget as(String alias) {
		return new MenuLayoutSectionWidget(DSL.name(alias), this);
	}

	@Override
	public MenuLayoutSectionWidget as(Name alias) {
		return new MenuLayoutSectionWidget(alias, this);
	}

	@Override
	public MenuLayoutSectionWidget as(Table<?> alias) {
		return new MenuLayoutSectionWidget(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidget rename(String name) {
		return new MenuLayoutSectionWidget(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidget rename(Name name) {
		return new MenuLayoutSectionWidget(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public MenuLayoutSectionWidget rename(Table<?> name) {
		return new MenuLayoutSectionWidget(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget where(Condition condition) {
		return new MenuLayoutSectionWidget(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidget where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidget where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidget where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public MenuLayoutSectionWidget where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public MenuLayoutSectionWidget whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
