/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.EventModel.EventModelPath;
import ch.rodano.core.model.jooq.tables.PaymentPlan.PaymentPlanPath;
import ch.rodano.core.model.jooq.tables.PaymentStepDistribution.PaymentStepDistributionPath;
import ch.rodano.core.model.jooq.tables.records.PaymentStepRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentStep extends TableImpl<PaymentStepRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>payment_step</code>
	 */
	public static final PaymentStep PAYMENT_STEP = new PaymentStep();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PaymentStepRecord> getRecordType() {
		return PaymentStepRecord.class;
	}

	/**
	 * The column <code>payment_step.payment_step_id</code>.
	 */
	public final TableField<PaymentStepRecord, UUID> PAYMENT_STEP_ID = createField(DSL.name("payment_step_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>payment_step.project_id</code>.
	 */
	public final TableField<PaymentStepRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>payment_step.payment_plan_id</code>.
	 */
	public final TableField<PaymentStepRecord, UUID> PAYMENT_PLAN_ID = createField(DSL.name("payment_plan_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>payment_step.code</code>.
	 */
	public final TableField<PaymentStepRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>payment_step.repeatable</code>.
	 */
	public final TableField<PaymentStepRecord, Boolean> REPEATABLE = createField(DSL.name("repeatable"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>payment_step.event_model_id</code>.
	 */
	public final TableField<PaymentStepRecord, UUID> EVENT_MODEL_ID = createField(DSL.name("event_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>payment_step.shortname</code>.
	 */
	public final TableField<PaymentStepRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>payment_step.longname</code>.
	 */
	public final TableField<PaymentStepRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>payment_step.description</code>.
	 */
	public final TableField<PaymentStepRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>payment_step.sort_order</code>.
	 */
	public final TableField<PaymentStepRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	private PaymentStep(Name alias, Table<PaymentStepRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private PaymentStep(Name alias, Table<PaymentStepRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>payment_step</code> table reference
	 */
	public PaymentStep(String alias) {
		this(DSL.name(alias), PAYMENT_STEP);
	}

	/**
	 * Create an aliased <code>payment_step</code> table reference
	 */
	public PaymentStep(Name alias) {
		this(alias, PAYMENT_STEP);
	}

	/**
	 * Create a <code>payment_step</code> table reference
	 */
	public PaymentStep() {
		this(DSL.name("payment_step"), null);
	}

	public <O extends Record> PaymentStep(Table<O> path, ForeignKey<O, PaymentStepRecord> childPath, InverseForeignKey<O, PaymentStepRecord> parentPath) {
		super(path, childPath, parentPath, PAYMENT_STEP);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class PaymentStepPath extends PaymentStep implements Path<PaymentStepRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> PaymentStepPath(Table<O> path, ForeignKey<O, PaymentStepRecord> childPath, InverseForeignKey<O, PaymentStepRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private PaymentStepPath(Name alias, Table<PaymentStepRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public PaymentStepPath as(String alias) {
			return new PaymentStepPath(DSL.name(alias), this);
		}

		@Override
		public PaymentStepPath as(Name alias) {
			return new PaymentStepPath(alias, this);
		}

		@Override
		public PaymentStepPath as(Table<?> alias) {
			return new PaymentStepPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.PAYMENT_STEP_IDX_PAYMENT_STEP_EVENT, Indexes.PAYMENT_STEP_IDX_PAYMENT_STEP_PLAN);
	}

	@Override
	public UniqueKey<PaymentStepRecord> getPrimaryKey() {
		return Keys.KEY_PAYMENT_STEP_PRIMARY;
	}

	@Override
	public List<UniqueKey<PaymentStepRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_PAYMENT_STEP_UQ_PAYMENT_STEP_CODE, Keys.KEY_PAYMENT_STEP_UQ_PAYMENT_STEP_ID);
	}

	@Override
	public List<ForeignKey<PaymentStepRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_PAYMENT_STEP_EVENT_MODEL, Keys.FK_PAYMENT_STEP_PLAN);
	}

	private transient EventModelPath _eventModel;

	/**
	 * Get the implicit join path to the <code>event_model</code> table.
	 */
	public EventModelPath eventModel() {
		if (_eventModel == null)
			_eventModel = new EventModelPath(this, Keys.FK_PAYMENT_STEP_EVENT_MODEL, null);

		return _eventModel;
	}

	private transient PaymentPlanPath _paymentPlan;

	/**
	 * Get the implicit join path to the <code>payment_plan</code> table.
	 */
	public PaymentPlanPath paymentPlan() {
		if (_paymentPlan == null)
			_paymentPlan = new PaymentPlanPath(this, Keys.FK_PAYMENT_STEP_PLAN, null);

		return _paymentPlan;
	}

	private transient PaymentStepDistributionPath _paymentStepDistribution;

	/**
	 * Get the implicit to-many join path to the
	 * <code>payment_step_distribution</code> table
	 */
	public PaymentStepDistributionPath paymentStepDistribution() {
		if (_paymentStepDistribution == null)
			_paymentStepDistribution = new PaymentStepDistributionPath(this, null, Keys.FK_PAYMENT_STEP_DIST_STEP.getInverseKey());

		return _paymentStepDistribution;
	}

	@Override
	public List<Check<PaymentStepRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public PaymentStep as(String alias) {
		return new PaymentStep(DSL.name(alias), this);
	}

	@Override
	public PaymentStep as(Name alias) {
		return new PaymentStep(alias, this);
	}

	@Override
	public PaymentStep as(Table<?> alias) {
		return new PaymentStep(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public PaymentStep rename(String name) {
		return new PaymentStep(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public PaymentStep rename(Name name) {
		return new PaymentStep(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public PaymentStep rename(Table<?> name) {
		return new PaymentStep(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep where(Condition condition) {
		return new PaymentStep(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public PaymentStep where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public PaymentStep where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public PaymentStep where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public PaymentStep where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public PaymentStep whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
