/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.ProfileScopeModelRightsRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProfileScopeModelRights extends TableImpl<ProfileScopeModelRightsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>profile_scope_model_rights</code>
	 */
	public static final ProfileScopeModelRights PROFILE_SCOPE_MODEL_RIGHTS = new ProfileScopeModelRights();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ProfileScopeModelRightsRecord> getRecordType() {
		return ProfileScopeModelRightsRecord.class;
	}

	/**
	 * The column <code>profile_scope_model_rights.project_id</code>.
	 */
	public final TableField<ProfileScopeModelRightsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>profile_scope_model_rights.profile_id</code>.
	 */
	public final TableField<ProfileScopeModelRightsRecord, UUID> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>profile_scope_model_rights.scope_model_id</code>.
	 */
	public final TableField<ProfileScopeModelRightsRecord, UUID> SCOPE_MODEL_ID = createField(DSL.name("scope_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>profile_scope_model_rights.can_read</code>.
	 */
	public final TableField<ProfileScopeModelRightsRecord, Boolean> CAN_READ = createField(DSL.name("can_read"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>profile_scope_model_rights.can_write</code>.
	 */
	public final TableField<ProfileScopeModelRightsRecord, Boolean> CAN_WRITE = createField(DSL.name("can_write"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	private ProfileScopeModelRights(Name alias, Table<ProfileScopeModelRightsRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ProfileScopeModelRights(Name alias, Table<ProfileScopeModelRightsRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>profile_scope_model_rights</code> table reference
	 */
	public ProfileScopeModelRights(String alias) {
		this(DSL.name(alias), PROFILE_SCOPE_MODEL_RIGHTS);
	}

	/**
	 * Create an aliased <code>profile_scope_model_rights</code> table reference
	 */
	public ProfileScopeModelRights(Name alias) {
		this(alias, PROFILE_SCOPE_MODEL_RIGHTS);
	}

	/**
	 * Create a <code>profile_scope_model_rights</code> table reference
	 */
	public ProfileScopeModelRights() {
		this(DSL.name("profile_scope_model_rights"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ProfileScopeModelRightsRecord> getPrimaryKey() {
		return Keys.KEY_PROFILE_SCOPE_MODEL_RIGHTS_PRIMARY;
	}

	@Override
	public ProfileScopeModelRights as(String alias) {
		return new ProfileScopeModelRights(DSL.name(alias), this);
	}

	@Override
	public ProfileScopeModelRights as(Name alias) {
		return new ProfileScopeModelRights(alias, this);
	}

	@Override
	public ProfileScopeModelRights as(Table<?> alias) {
		return new ProfileScopeModelRights(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ProfileScopeModelRights rename(String name) {
		return new ProfileScopeModelRights(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ProfileScopeModelRights rename(Name name) {
		return new ProfileScopeModelRights(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ProfileScopeModelRights rename(Table<?> name) {
		return new ProfileScopeModelRights(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights where(Condition condition) {
		return new ProfileScopeModelRights(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ProfileScopeModelRights where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ProfileScopeModelRights where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ProfileScopeModelRights where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ProfileScopeModelRights where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ProfileScopeModelRights whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
