/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.ReportRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Report extends TableImpl<ReportRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>report</code>
	 */
	public static final Report REPORT = new Report();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReportRecord> getRecordType() {
		return ReportRecord.class;
	}

	/**
	 * The column <code>report.report_id</code>.
	 */
	public final TableField<ReportRecord, UUID> REPORT_ID = createField(DSL.name("report_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>report.project_id</code>.
	 */
	public final TableField<ReportRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>report.code</code>.
	 */
	public final TableField<ReportRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>report.dataset_model_id</code>.
	 */
	public final TableField<ReportRecord, UUID> DATASET_MODEL_ID = createField(DSL.name("dataset_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>report.workflow_id</code>.
	 */
	public final TableField<ReportRecord, UUID> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>report.shortname</code>.
	 */
	public final TableField<ReportRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>report.longname</code>.
	 */
	public final TableField<ReportRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>report.description</code>.
	 */
	public final TableField<ReportRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	private Report(Name alias, Table<ReportRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Report(Name alias, Table<ReportRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>report</code> table reference
	 */
	public Report(String alias) {
		this(DSL.name(alias), REPORT);
	}

	/**
	 * Create an aliased <code>report</code> table reference
	 */
	public Report(Name alias) {
		this(alias, REPORT);
	}

	/**
	 * Create a <code>report</code> table reference
	 */
	public Report() {
		this(DSL.name("report"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ReportRecord> getPrimaryKey() {
		return Keys.KEY_REPORT_PRIMARY;
	}

	@Override
	public List<Check<ReportRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public Report as(String alias) {
		return new Report(DSL.name(alias), this);
	}

	@Override
	public Report as(Name alias) {
		return new Report(alias, this);
	}

	@Override
	public Report as(Table<?> alias) {
		return new Report(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Report rename(String name) {
		return new Report(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Report rename(Name name) {
		return new Report(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Report rename(Table<?> name) {
		return new Report(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report where(Condition condition) {
		return new Report(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Report where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Report where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Report where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Report where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Report whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
