/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.helpers.configuration.DateConverter;
import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.RoleAuditRecord;
import ch.rodano.core.model.jooqutils.AuditTable;

import java.time.ZonedDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleAudit extends TableImpl<RoleAuditRecord> implements AuditTable {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>role_audit</code>
	 */
	public static final RoleAudit ROLE_AUDIT = new RoleAudit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RoleAuditRecord> getRecordType() {
		return RoleAuditRecord.class;
	}

	/**
	 * The column <code>role_audit.pk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> PK = createField(DSL.name("pk"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

	/**
	 * The column <code>role_audit.project_id</code>.
	 */
	public final TableField<RoleAuditRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>role_audit.audit_action_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> AUDIT_ACTION_FK = createField(DSL.name("audit_action_fk"), SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>role_audit.audit_datetime</code>.
	 */
	public final TableField<RoleAuditRecord, ZonedDateTime> AUDIT_DATETIME = createField(DSL.name("audit_datetime"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "", new DateConverter());

	/**
	 * The column <code>role_audit.audit_actor</code>.
	 */
	public final TableField<RoleAuditRecord, String> AUDIT_ACTOR = createField(DSL.name("audit_actor"), SQLDataType.VARCHAR(200).nullable(false), this, "");

	/**
	 * The column <code>role_audit.audit_user_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> AUDIT_USER_FK = createField(DSL.name("audit_user_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>role_audit.audit_robot_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> AUDIT_ROBOT_FK = createField(DSL.name("audit_robot_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>role_audit.audit_context</code>.
	 */
	public final TableField<RoleAuditRecord, String> AUDIT_CONTEXT = createField(DSL.name("audit_context"), SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>role_audit.audit_object_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> AUDIT_OBJECT_FK = createField(DSL.name("audit_object_fk"), SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>role_audit.user_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> USER_FK = createField(DSL.name("user_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>role_audit.robot_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> ROBOT_FK = createField(DSL.name("robot_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>role_audit.scope_fk</code>.
	 */
	public final TableField<RoleAuditRecord, Long> SCOPE_FK = createField(DSL.name("scope_fk"), SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>role_audit.profile_id</code>.
	 */
	public final TableField<RoleAuditRecord, UUID> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>role_audit.status</code>.
	 */
	public final TableField<RoleAuditRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(50).nullable(false), this, "");

	private RoleAudit(Name alias, Table<RoleAuditRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private RoleAudit(Name alias, Table<RoleAuditRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>role_audit</code> table reference
	 */
	public RoleAudit(String alias) {
		this(DSL.name(alias), ROLE_AUDIT);
	}

	/**
	 * Create an aliased <code>role_audit</code> table reference
	 */
	public RoleAudit(Name alias) {
		this(alias, ROLE_AUDIT);
	}

	/**
	 * Create a <code>role_audit</code> table reference
	 */
	public RoleAudit() {
		this(DSL.name("role_audit"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<RoleAuditRecord, Long> getIdentity() {
		return (Identity<RoleAuditRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<RoleAuditRecord> getPrimaryKey() {
		return Keys.KEY_ROLE_AUDIT_PRIMARY;
	}

	@Override
	public RoleAudit as(String alias) {
		return new RoleAudit(DSL.name(alias), this);
	}

	@Override
	public RoleAudit as(Name alias) {
		return new RoleAudit(alias, this);
	}

	@Override
	public RoleAudit as(Table<?> alias) {
		return new RoleAudit(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RoleAudit rename(String name) {
		return new RoleAudit(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RoleAudit rename(Name name) {
		return new RoleAudit(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RoleAudit rename(Table<?> name) {
		return new RoleAudit(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit where(Condition condition) {
		return new RoleAudit(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RoleAudit where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RoleAudit where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RoleAudit where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RoleAudit where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RoleAudit whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
