/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.RuleCriterion.RuleCriterionPath;
import ch.rodano.core.model.jooq.tables.records.RuleCriterionValueRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuleCriterionValue extends TableImpl<RuleCriterionValueRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>rule_criterion_value</code>
	 */
	public static final RuleCriterionValue RULE_CRITERION_VALUE = new RuleCriterionValue();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RuleCriterionValueRecord> getRecordType() {
		return RuleCriterionValueRecord.class;
	}

	/**
	 * The column <code>rule_criterion_value.project_id</code>.
	 */
	public final TableField<RuleCriterionValueRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>rule_criterion_value.criterion_id</code>.
	 */
	public final TableField<RuleCriterionValueRecord, UUID> CRITERION_ID = createField(DSL.name("criterion_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>rule_criterion_value.value_order</code>.
	 */
	public final TableField<RuleCriterionValueRecord, Integer> VALUE_ORDER = createField(DSL.name("value_order"), SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>rule_criterion_value.value_text</code>.
	 */
	public final TableField<RuleCriterionValueRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), SQLDataType.VARCHAR(512).nullable(false), this, "");

	private RuleCriterionValue(Name alias, Table<RuleCriterionValueRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private RuleCriterionValue(Name alias, Table<RuleCriterionValueRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>rule_criterion_value</code> table reference
	 */
	public RuleCriterionValue(String alias) {
		this(DSL.name(alias), RULE_CRITERION_VALUE);
	}

	/**
	 * Create an aliased <code>rule_criterion_value</code> table reference
	 */
	public RuleCriterionValue(Name alias) {
		this(alias, RULE_CRITERION_VALUE);
	}

	/**
	 * Create a <code>rule_criterion_value</code> table reference
	 */
	public RuleCriterionValue() {
		this(DSL.name("rule_criterion_value"), null);
	}

	public <O extends Record> RuleCriterionValue(Table<O> path, ForeignKey<O, RuleCriterionValueRecord> childPath, InverseForeignKey<O, RuleCriterionValueRecord> parentPath) {
		super(path, childPath, parentPath, RULE_CRITERION_VALUE);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class RuleCriterionValuePath extends RuleCriterionValue implements Path<RuleCriterionValueRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> RuleCriterionValuePath(Table<O> path, ForeignKey<O, RuleCriterionValueRecord> childPath, InverseForeignKey<O, RuleCriterionValueRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private RuleCriterionValuePath(Name alias, Table<RuleCriterionValueRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public RuleCriterionValuePath as(String alias) {
			return new RuleCriterionValuePath(DSL.name(alias), this);
		}

		@Override
		public RuleCriterionValuePath as(Name alias) {
			return new RuleCriterionValuePath(alias, this);
		}

		@Override
		public RuleCriterionValuePath as(Table<?> alias) {
			return new RuleCriterionValuePath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<RuleCriterionValueRecord> getPrimaryKey() {
		return Keys.KEY_RULE_CRITERION_VALUE_PRIMARY;
	}

	@Override
	public List<ForeignKey<RuleCriterionValueRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_CONSTRAINT_CONDITION_CRITERION_VALUE);
	}

	private transient RuleCriterionPath _ruleCriterion;

	/**
	 * Get the implicit join path to the <code>rule_criterion</code> table.
	 */
	public RuleCriterionPath ruleCriterion() {
		if (_ruleCriterion == null)
			_ruleCriterion = new RuleCriterionPath(this, Keys.FK_CONSTRAINT_CONDITION_CRITERION_VALUE, null);

		return _ruleCriterion;
	}

	@Override
	public RuleCriterionValue as(String alias) {
		return new RuleCriterionValue(DSL.name(alias), this);
	}

	@Override
	public RuleCriterionValue as(Name alias) {
		return new RuleCriterionValue(alias, this);
	}

	@Override
	public RuleCriterionValue as(Table<?> alias) {
		return new RuleCriterionValue(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleCriterionValue rename(String name) {
		return new RuleCriterionValue(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleCriterionValue rename(Name name) {
		return new RuleCriterionValue(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleCriterionValue rename(Table<?> name) {
		return new RuleCriterionValue(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue where(Condition condition) {
		return new RuleCriterionValue(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleCriterionValue where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleCriterionValue where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleCriterionValue where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleCriterionValue where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleCriterionValue whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
