/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.Project.ProjectPath;
import ch.rodano.core.model.jooq.tables.records.RuleDefinitionPropertyRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuleDefinitionProperty extends TableImpl<RuleDefinitionPropertyRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>rule_definition_property</code>
	 */
	public static final RuleDefinitionProperty RULE_DEFINITION_PROPERTY = new RuleDefinitionProperty();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RuleDefinitionPropertyRecord> getRecordType() {
		return RuleDefinitionPropertyRecord.class;
	}

	/**
	 * The column
	 * <code>rule_definition_property.rule_definition_property_id</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, UUID> RULE_DEFINITION_PROPERTY_ID = createField(DSL.name("rule_definition_property_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>rule_definition_property.project_id</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>rule_definition_property.code</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>rule_definition_property.label</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>rule_definition_property.entity_id</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.VARCHAR(64).nullable(false), this, "");

	/**
	 * The column <code>rule_definition_property.target</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> TARGET = createField(DSL.name("target"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>rule_definition_property.type</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(64).nullable(false), this, "");

	/**
	 * The column <code>rule_definition_property.configuration_entity</code>.
	 */
	public final TableField<RuleDefinitionPropertyRecord, String> CONFIGURATION_ENTITY = createField(DSL.name("configuration_entity"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	private RuleDefinitionProperty(Name alias, Table<RuleDefinitionPropertyRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private RuleDefinitionProperty(Name alias, Table<RuleDefinitionPropertyRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>rule_definition_property</code> table reference
	 */
	public RuleDefinitionProperty(String alias) {
		this(DSL.name(alias), RULE_DEFINITION_PROPERTY);
	}

	/**
	 * Create an aliased <code>rule_definition_property</code> table reference
	 */
	public RuleDefinitionProperty(Name alias) {
		this(alias, RULE_DEFINITION_PROPERTY);
	}

	/**
	 * Create a <code>rule_definition_property</code> table reference
	 */
	public RuleDefinitionProperty() {
		this(DSL.name("rule_definition_property"), null);
	}

	public <O extends Record> RuleDefinitionProperty(Table<O> path, ForeignKey<O, RuleDefinitionPropertyRecord> childPath, InverseForeignKey<O, RuleDefinitionPropertyRecord> parentPath) {
		super(path, childPath, parentPath, RULE_DEFINITION_PROPERTY);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class RuleDefinitionPropertyPath extends RuleDefinitionProperty implements Path<RuleDefinitionPropertyRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> RuleDefinitionPropertyPath(Table<O> path, ForeignKey<O, RuleDefinitionPropertyRecord> childPath, InverseForeignKey<O, RuleDefinitionPropertyRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private RuleDefinitionPropertyPath(Name alias, Table<RuleDefinitionPropertyRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public RuleDefinitionPropertyPath as(String alias) {
			return new RuleDefinitionPropertyPath(DSL.name(alias), this);
		}

		@Override
		public RuleDefinitionPropertyPath as(Name alias) {
			return new RuleDefinitionPropertyPath(alias, this);
		}

		@Override
		public RuleDefinitionPropertyPath as(Table<?> alias) {
			return new RuleDefinitionPropertyPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<RuleDefinitionPropertyRecord> getPrimaryKey() {
		return Keys.KEY_RULE_DEFINITION_PROPERTY_PRIMARY;
	}

	@Override
	public List<UniqueKey<RuleDefinitionPropertyRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_RULE_DEFINITION_PROPERTY_UQ_RULE_DEFINITION_PROPERTY_CODE);
	}

	@Override
	public List<ForeignKey<RuleDefinitionPropertyRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_RULE_DEF_PROP_PROJECT);
	}

	private transient ProjectPath _project;

	/**
	 * Get the implicit join path to the <code>project</code> table.
	 */
	public ProjectPath project() {
		if (_project == null)
			_project = new ProjectPath(this, Keys.FK_RULE_DEF_PROP_PROJECT, null);

		return _project;
	}

	@Override
	public RuleDefinitionProperty as(String alias) {
		return new RuleDefinitionProperty(DSL.name(alias), this);
	}

	@Override
	public RuleDefinitionProperty as(Name alias) {
		return new RuleDefinitionProperty(alias, this);
	}

	@Override
	public RuleDefinitionProperty as(Table<?> alias) {
		return new RuleDefinitionProperty(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionProperty rename(String name) {
		return new RuleDefinitionProperty(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionProperty rename(Name name) {
		return new RuleDefinitionProperty(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionProperty rename(Table<?> name) {
		return new RuleDefinitionProperty(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty where(Condition condition) {
		return new RuleDefinitionProperty(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionProperty where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionProperty where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionProperty where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionProperty where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionProperty whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
