/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.Project.ProjectPath;
import ch.rodano.core.model.jooq.tables.RuleDefinitionAction.RuleDefinitionActionPath;
import ch.rodano.core.model.jooq.tables.records.RuleDefinitionActionParameterRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuleDefinitionActionParameter extends TableImpl<RuleDefinitionActionParameterRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>rule_definition_action_parameter</code>
	 */
	public static final RuleDefinitionActionParameter RULE_DEFINITION_ACTION_PARAMETER = new RuleDefinitionActionParameter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RuleDefinitionActionParameterRecord> getRecordType() {
		return RuleDefinitionActionParameterRecord.class;
	}

	/**
	 * The column <code>rule_definition_action_parameter.project_id</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>rule_definition_action_parameter.rule_definition_action_id</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, UUID> RULE_DEFINITION_ACTION_ID = createField(DSL.name("rule_definition_action_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>rule_definition_action_parameter.param_code</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, String> PARAM_CODE = createField(DSL.name("param_code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>rule_definition_action_parameter.label</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>rule_definition_action_parameter.data_entity</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, String> DATA_ENTITY = createField(DSL.name("data_entity"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column
	 * <code>rule_definition_action_parameter.configuration_entity</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, String> CONFIGURATION_ENTITY = createField(DSL.name("configuration_entity"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>rule_definition_action_parameter.sort_order</code>.
	 */
	public final TableField<RuleDefinitionActionParameterRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

	private RuleDefinitionActionParameter(Name alias, Table<RuleDefinitionActionParameterRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private RuleDefinitionActionParameter(Name alias, Table<RuleDefinitionActionParameterRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>rule_definition_action_parameter</code> table
	 * reference
	 */
	public RuleDefinitionActionParameter(String alias) {
		this(DSL.name(alias), RULE_DEFINITION_ACTION_PARAMETER);
	}

	/**
	 * Create an aliased <code>rule_definition_action_parameter</code> table
	 * reference
	 */
	public RuleDefinitionActionParameter(Name alias) {
		this(alias, RULE_DEFINITION_ACTION_PARAMETER);
	}

	/**
	 * Create a <code>rule_definition_action_parameter</code> table reference
	 */
	public RuleDefinitionActionParameter() {
		this(DSL.name("rule_definition_action_parameter"), null);
	}

	public <O extends Record> RuleDefinitionActionParameter(Table<O> path, ForeignKey<O, RuleDefinitionActionParameterRecord> childPath, InverseForeignKey<O, RuleDefinitionActionParameterRecord> parentPath) {
		super(path, childPath, parentPath, RULE_DEFINITION_ACTION_PARAMETER);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class RuleDefinitionActionParameterPath extends RuleDefinitionActionParameter implements Path<RuleDefinitionActionParameterRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> RuleDefinitionActionParameterPath(Table<O> path, ForeignKey<O, RuleDefinitionActionParameterRecord> childPath, InverseForeignKey<O, RuleDefinitionActionParameterRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private RuleDefinitionActionParameterPath(Name alias, Table<RuleDefinitionActionParameterRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public RuleDefinitionActionParameterPath as(String alias) {
			return new RuleDefinitionActionParameterPath(DSL.name(alias), this);
		}

		@Override
		public RuleDefinitionActionParameterPath as(Name alias) {
			return new RuleDefinitionActionParameterPath(alias, this);
		}

		@Override
		public RuleDefinitionActionParameterPath as(Table<?> alias) {
			return new RuleDefinitionActionParameterPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.RULE_DEFINITION_ACTION_PARAMETER_IDX_RULE_DEF_ACTION_PARAM_PARENT);
	}

	@Override
	public UniqueKey<RuleDefinitionActionParameterRecord> getPrimaryKey() {
		return Keys.KEY_RULE_DEFINITION_ACTION_PARAMETER_PRIMARY;
	}

	@Override
	public List<ForeignKey<RuleDefinitionActionParameterRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_RULE_DEF_ACTION_PARAM_ACTION, Keys.FK_RULE_DEF_ACTION_PARAM_PROJECT);
	}

	private transient RuleDefinitionActionPath _ruleDefinitionAction;

	/**
	 * Get the implicit join path to the <code>rule_definition_action</code> table.
	 */
	public RuleDefinitionActionPath ruleDefinitionAction() {
		if (_ruleDefinitionAction == null)
			_ruleDefinitionAction = new RuleDefinitionActionPath(this, Keys.FK_RULE_DEF_ACTION_PARAM_ACTION, null);

		return _ruleDefinitionAction;
	}

	private transient ProjectPath _project;

	/**
	 * Get the implicit join path to the <code>project</code> table.
	 */
	public ProjectPath project() {
		if (_project == null)
			_project = new ProjectPath(this, Keys.FK_RULE_DEF_ACTION_PARAM_PROJECT, null);

		return _project;
	}

	@Override
	public RuleDefinitionActionParameter as(String alias) {
		return new RuleDefinitionActionParameter(DSL.name(alias), this);
	}

	@Override
	public RuleDefinitionActionParameter as(Name alias) {
		return new RuleDefinitionActionParameter(alias, this);
	}

	@Override
	public RuleDefinitionActionParameter as(Table<?> alias) {
		return new RuleDefinitionActionParameter(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionActionParameter rename(String name) {
		return new RuleDefinitionActionParameter(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionActionParameter rename(Name name) {
		return new RuleDefinitionActionParameter(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public RuleDefinitionActionParameter rename(Table<?> name) {
		return new RuleDefinitionActionParameter(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter where(Condition condition) {
		return new RuleDefinitionActionParameter(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionActionParameter where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionActionParameter where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionActionParameter where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public RuleDefinitionActionParameter where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public RuleDefinitionActionParameter whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
