/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.ScopeModelParentRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScopeModelParent extends TableImpl<ScopeModelParentRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>scope_model_parent</code>
	 */
	public static final ScopeModelParent SCOPE_MODEL_PARENT = new ScopeModelParent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScopeModelParentRecord> getRecordType() {
		return ScopeModelParentRecord.class;
	}

	/**
	 * The column <code>scope_model_parent.project_id</code>.
	 */
	public final TableField<ScopeModelParentRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>scope_model_parent.child_scope_model_id</code>.
	 */
	public final TableField<ScopeModelParentRecord, UUID> CHILD_SCOPE_MODEL_ID = createField(DSL.name("child_scope_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>scope_model_parent.parent_scope_model_id</code>.
	 */
	public final TableField<ScopeModelParentRecord, UUID> PARENT_SCOPE_MODEL_ID = createField(DSL.name("parent_scope_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>scope_model_parent.is_default</code>.
	 */
	public final TableField<ScopeModelParentRecord, Boolean> IS_DEFAULT = createField(DSL.name("is_default"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>scope_model_parent.parent_order</code>.
	 */
	public final TableField<ScopeModelParentRecord, Integer> PARENT_ORDER = createField(DSL.name("parent_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	private ScopeModelParent(Name alias, Table<ScopeModelParentRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ScopeModelParent(Name alias, Table<ScopeModelParentRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>scope_model_parent</code> table reference
	 */
	public ScopeModelParent(String alias) {
		this(DSL.name(alias), SCOPE_MODEL_PARENT);
	}

	/**
	 * Create an aliased <code>scope_model_parent</code> table reference
	 */
	public ScopeModelParent(Name alias) {
		this(alias, SCOPE_MODEL_PARENT);
	}

	/**
	 * Create a <code>scope_model_parent</code> table reference
	 */
	public ScopeModelParent() {
		this(DSL.name("scope_model_parent"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ScopeModelParentRecord> getPrimaryKey() {
		return Keys.KEY_SCOPE_MODEL_PARENT_PRIMARY;
	}

	@Override
	public ScopeModelParent as(String alias) {
		return new ScopeModelParent(DSL.name(alias), this);
	}

	@Override
	public ScopeModelParent as(Name alias) {
		return new ScopeModelParent(alias, this);
	}

	@Override
	public ScopeModelParent as(Table<?> alias) {
		return new ScopeModelParent(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelParent rename(String name) {
		return new ScopeModelParent(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelParent rename(Name name) {
		return new ScopeModelParent(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelParent rename(Table<?> name) {
		return new ScopeModelParent(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent where(Condition condition) {
		return new ScopeModelParent(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelParent where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelParent where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelParent where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelParent where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelParent whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
