/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.ScopeModelWorkflowStateSelectorRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScopeModelWorkflowStateSelector extends TableImpl<ScopeModelWorkflowStateSelectorRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>scope_model_workflow_state_selector</code>
	 */
	public static final ScopeModelWorkflowStateSelector SCOPE_MODEL_WORKFLOW_STATE_SELECTOR = new ScopeModelWorkflowStateSelector();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScopeModelWorkflowStateSelectorRecord> getRecordType() {
		return ScopeModelWorkflowStateSelectorRecord.class;
	}

	/**
	 * The column <code>scope_model_workflow_state_selector.project_id</code>.
	 */
	public final TableField<ScopeModelWorkflowStateSelectorRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>scope_model_workflow_state_selector.scope_model_id</code>.
	 */
	public final TableField<ScopeModelWorkflowStateSelectorRecord, UUID> SCOPE_MODEL_ID = createField(DSL.name("scope_model_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>scope_model_workflow_state_selector.workflow_id</code>.
	 */
	public final TableField<ScopeModelWorkflowStateSelectorRecord, UUID> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>scope_model_workflow_state_selector.workflow_state_id</code>.
	 */
	public final TableField<ScopeModelWorkflowStateSelectorRecord, UUID> WORKFLOW_STATE_ID = createField(DSL.name("workflow_state_id"), SQLDataType.UUID.nullable(false), this, "");

	private ScopeModelWorkflowStateSelector(Name alias, Table<ScopeModelWorkflowStateSelectorRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private ScopeModelWorkflowStateSelector(Name alias, Table<ScopeModelWorkflowStateSelectorRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>scope_model_workflow_state_selector</code> table
	 * reference
	 */
	public ScopeModelWorkflowStateSelector(String alias) {
		this(DSL.name(alias), SCOPE_MODEL_WORKFLOW_STATE_SELECTOR);
	}

	/**
	 * Create an aliased <code>scope_model_workflow_state_selector</code> table
	 * reference
	 */
	public ScopeModelWorkflowStateSelector(Name alias) {
		this(alias, SCOPE_MODEL_WORKFLOW_STATE_SELECTOR);
	}

	/**
	 * Create a <code>scope_model_workflow_state_selector</code> table reference
	 */
	public ScopeModelWorkflowStateSelector() {
		this(DSL.name("scope_model_workflow_state_selector"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<ScopeModelWorkflowStateSelectorRecord> getPrimaryKey() {
		return Keys.KEY_SCOPE_MODEL_WORKFLOW_STATE_SELECTOR_PRIMARY;
	}

	@Override
	public ScopeModelWorkflowStateSelector as(String alias) {
		return new ScopeModelWorkflowStateSelector(DSL.name(alias), this);
	}

	@Override
	public ScopeModelWorkflowStateSelector as(Name alias) {
		return new ScopeModelWorkflowStateSelector(alias, this);
	}

	@Override
	public ScopeModelWorkflowStateSelector as(Table<?> alias) {
		return new ScopeModelWorkflowStateSelector(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector rename(String name) {
		return new ScopeModelWorkflowStateSelector(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector rename(Name name) {
		return new ScopeModelWorkflowStateSelector(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector rename(Table<?> name) {
		return new ScopeModelWorkflowStateSelector(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector where(Condition condition) {
		return new ScopeModelWorkflowStateSelector(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelWorkflowStateSelector where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelWorkflowStateSelector where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelWorkflowStateSelector where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public ScopeModelWorkflowStateSelector where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public ScopeModelWorkflowStateSelector whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
