/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.TimelineGraphSectionReferenceEntryRecord;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimelineGraphSectionReferenceEntry extends TableImpl<TimelineGraphSectionReferenceEntryRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of
	 * <code>timeline_graph_section_reference_entry</code>
	 */
	public static final TimelineGraphSectionReferenceEntry TIMELINE_GRAPH_SECTION_REFERENCE_ENTRY = new TimelineGraphSectionReferenceEntry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimelineGraphSectionReferenceEntryRecord> getRecordType() {
		return TimelineGraphSectionReferenceEntryRecord.class;
	}

	/**
	 * The column <code>timeline_graph_section_reference_entry.project_id</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>timeline_graph_section_reference_entry.timeline_graph_id</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, UUID> TIMELINE_GRAPH_ID = createField(DSL.name("timeline_graph_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>timeline_graph_section_reference_entry.graph_section_id</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, UUID> GRAPH_SECTION_ID = createField(DSL.name("graph_section_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>timeline_graph_section_reference_entry.graph_reference_id</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, UUID> GRAPH_REFERENCE_ID = createField(DSL.name("graph_reference_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section_reference_entry.timepoint</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, String> TIMEPOINT = createField(DSL.name("timepoint"), SQLDataType.VARCHAR(32).nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section_reference_entry.value</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, BigDecimal> VALUE = createField(DSL.name("value"), SQLDataType.DECIMAL(18, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section_reference_entry.label</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>timeline_graph_section_reference_entry.sort_order</code>.
	 */
	public final TableField<TimelineGraphSectionReferenceEntryRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	private TimelineGraphSectionReferenceEntry(Name alias, Table<TimelineGraphSectionReferenceEntryRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private TimelineGraphSectionReferenceEntry(Name alias, Table<TimelineGraphSectionReferenceEntryRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>timeline_graph_section_reference_entry</code> table
	 * reference
	 */
	public TimelineGraphSectionReferenceEntry(String alias) {
		this(DSL.name(alias), TIMELINE_GRAPH_SECTION_REFERENCE_ENTRY);
	}

	/**
	 * Create an aliased <code>timeline_graph_section_reference_entry</code> table
	 * reference
	 */
	public TimelineGraphSectionReferenceEntry(Name alias) {
		this(alias, TIMELINE_GRAPH_SECTION_REFERENCE_ENTRY);
	}

	/**
	 * Create a <code>timeline_graph_section_reference_entry</code> table reference
	 */
	public TimelineGraphSectionReferenceEntry() {
		this(DSL.name("timeline_graph_section_reference_entry"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TimelineGraphSectionReferenceEntryRecord> getPrimaryKey() {
		return Keys.KEY_TIMELINE_GRAPH_SECTION_REFERENCE_ENTRY_PRIMARY;
	}

	@Override
	public TimelineGraphSectionReferenceEntry as(String alias) {
		return new TimelineGraphSectionReferenceEntry(DSL.name(alias), this);
	}

	@Override
	public TimelineGraphSectionReferenceEntry as(Name alias) {
		return new TimelineGraphSectionReferenceEntry(alias, this);
	}

	@Override
	public TimelineGraphSectionReferenceEntry as(Table<?> alias) {
		return new TimelineGraphSectionReferenceEntry(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry rename(String name) {
		return new TimelineGraphSectionReferenceEntry(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry rename(Name name) {
		return new TimelineGraphSectionReferenceEntry(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry rename(Table<?> name) {
		return new TimelineGraphSectionReferenceEntry(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry where(Condition condition) {
		return new TimelineGraphSectionReferenceEntry(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionReferenceEntry where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionReferenceEntry where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionReferenceEntry where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionReferenceEntry where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionReferenceEntry whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
