/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.FieldModel.FieldModelPath;
import ch.rodano.core.model.jooq.tables.TimelineGraphSection.TimelineGraphSectionPath;
import ch.rodano.core.model.jooq.tables.records.TimelineGraphSectionMetaFieldRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimelineGraphSectionMetaField extends TableImpl<TimelineGraphSectionMetaFieldRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>timeline_graph_section_meta_field</code>
	 */
	public static final TimelineGraphSectionMetaField TIMELINE_GRAPH_SECTION_META_FIELD = new TimelineGraphSectionMetaField();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimelineGraphSectionMetaFieldRecord> getRecordType() {
		return TimelineGraphSectionMetaFieldRecord.class;
	}

	/**
	 * The column <code>timeline_graph_section_meta_field.project_id</code>.
	 */
	public final TableField<TimelineGraphSectionMetaFieldRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section_meta_field.timeline_graph_id</code>.
	 */
	public final TableField<TimelineGraphSectionMetaFieldRecord, UUID> TIMELINE_GRAPH_ID = createField(DSL.name("timeline_graph_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section_meta_field.graph_section_id</code>.
	 */
	public final TableField<TimelineGraphSectionMetaFieldRecord, UUID> GRAPH_SECTION_ID = createField(DSL.name("graph_section_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section_meta_field.field_model_id</code>.
	 */
	public final TableField<TimelineGraphSectionMetaFieldRecord, UUID> FIELD_MODEL_ID = createField(DSL.name("field_model_id"), SQLDataType.UUID.nullable(false), this, "");

	private TimelineGraphSectionMetaField(Name alias, Table<TimelineGraphSectionMetaFieldRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private TimelineGraphSectionMetaField(Name alias, Table<TimelineGraphSectionMetaFieldRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>timeline_graph_section_meta_field</code> table
	 * reference
	 */
	public TimelineGraphSectionMetaField(String alias) {
		this(DSL.name(alias), TIMELINE_GRAPH_SECTION_META_FIELD);
	}

	/**
	 * Create an aliased <code>timeline_graph_section_meta_field</code> table
	 * reference
	 */
	public TimelineGraphSectionMetaField(Name alias) {
		this(alias, TIMELINE_GRAPH_SECTION_META_FIELD);
	}

	/**
	 * Create a <code>timeline_graph_section_meta_field</code> table reference
	 */
	public TimelineGraphSectionMetaField() {
		this(DSL.name("timeline_graph_section_meta_field"), null);
	}

	public <O extends Record> TimelineGraphSectionMetaField(Table<O> path, ForeignKey<O, TimelineGraphSectionMetaFieldRecord> childPath, InverseForeignKey<O, TimelineGraphSectionMetaFieldRecord> parentPath) {
		super(path, childPath, parentPath, TIMELINE_GRAPH_SECTION_META_FIELD);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class TimelineGraphSectionMetaFieldPath extends TimelineGraphSectionMetaField implements Path<TimelineGraphSectionMetaFieldRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> TimelineGraphSectionMetaFieldPath(Table<O> path, ForeignKey<O, TimelineGraphSectionMetaFieldRecord> childPath, InverseForeignKey<O, TimelineGraphSectionMetaFieldRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private TimelineGraphSectionMetaFieldPath(Name alias, Table<TimelineGraphSectionMetaFieldRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public TimelineGraphSectionMetaFieldPath as(String alias) {
			return new TimelineGraphSectionMetaFieldPath(DSL.name(alias), this);
		}

		@Override
		public TimelineGraphSectionMetaFieldPath as(Name alias) {
			return new TimelineGraphSectionMetaFieldPath(alias, this);
		}

		@Override
		public TimelineGraphSectionMetaFieldPath as(Table<?> alias) {
			return new TimelineGraphSectionMetaFieldPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TimelineGraphSectionMetaFieldRecord> getPrimaryKey() {
		return Keys.KEY_TIMELINE_GRAPH_SECTION_META_FIELD_PRIMARY;
	}

	@Override
	public List<ForeignKey<TimelineGraphSectionMetaFieldRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_TIMELINE_GRAPH_SECTION_META_FIELD_FIELD, Keys.FK_TIMELINE_GRAPH_SECTION_META_FIELD_GRAPH);
	}

	private transient FieldModelPath _fieldModel;

	/**
	 * Get the implicit join path to the <code>field_model</code> table.
	 */
	public FieldModelPath fieldModel() {
		if (_fieldModel == null)
			_fieldModel = new FieldModelPath(this, Keys.FK_TIMELINE_GRAPH_SECTION_META_FIELD_FIELD, null);

		return _fieldModel;
	}

	private transient TimelineGraphSectionPath _timelineGraphSection;

	/**
	 * Get the implicit join path to the <code>timeline_graph_section</code> table.
	 */
	public TimelineGraphSectionPath timelineGraphSection() {
		if (_timelineGraphSection == null)
			_timelineGraphSection = new TimelineGraphSectionPath(this, Keys.FK_TIMELINE_GRAPH_SECTION_META_FIELD_GRAPH, null);

		return _timelineGraphSection;
	}

	@Override
	public TimelineGraphSectionMetaField as(String alias) {
		return new TimelineGraphSectionMetaField(DSL.name(alias), this);
	}

	@Override
	public TimelineGraphSectionMetaField as(Name alias) {
		return new TimelineGraphSectionMetaField(alias, this);
	}

	@Override
	public TimelineGraphSectionMetaField as(Table<?> alias) {
		return new TimelineGraphSectionMetaField(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionMetaField rename(String name) {
		return new TimelineGraphSectionMetaField(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionMetaField rename(Name name) {
		return new TimelineGraphSectionMetaField(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSectionMetaField rename(Table<?> name) {
		return new TimelineGraphSectionMetaField(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField where(Condition condition) {
		return new TimelineGraphSectionMetaField(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionMetaField where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionMetaField where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionMetaField where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSectionMetaField where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSectionMetaField whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
