/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.enums.TimelineGraphSectionMark;
import ch.rodano.core.model.jooq.enums.TimelineGraphSectionScalePosition;
import ch.rodano.core.model.jooq.enums.TimelineGraphSectionType;
import ch.rodano.core.model.jooq.tables.records.TimelineGraphSectionRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimelineGraphSection extends TableImpl<TimelineGraphSectionRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>timeline_graph_section</code>
	 */
	public static final TimelineGraphSection TIMELINE_GRAPH_SECTION = new TimelineGraphSection();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TimelineGraphSectionRecord> getRecordType() {
		return TimelineGraphSectionRecord.class;
	}

	/**
	 * The column <code>timeline_graph_section.graph_section_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> GRAPH_SECTION_ID = createField(DSL.name("graph_section_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.project_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section.timeline_graph_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> TIMELINE_GRAPH_ID = createField(DSL.name("timeline_graph_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section.code</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>timeline_graph_section.type</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, TimelineGraphSectionType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(6).nullable(false).asEnumDataType(TimelineGraphSectionType.class), this, "");

	/**
	 * The column <code>timeline_graph_section.dataset_model_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> DATASET_MODEL_ID = createField(DSL.name("dataset_model_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.date_field_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> DATE_FIELD_ID = createField(DSL.name("date_field_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.end_date_field_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> END_DATE_FIELD_ID = createField(DSL.name("end_date_field_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.label_field_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> LABEL_FIELD_ID = createField(DSL.name("label_field_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.value_field_id</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, UUID> VALUE_FIELD_ID = createField(DSL.name("value_field_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>timeline_graph_section.hide_expected_event</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> HIDE_EXPECTED_EVENT = createField(DSL.name("hide_expected_event"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.hide_done_event</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> HIDE_DONE_EVENT = createField(DSL.name("hide_done_event"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.use_scope_paths</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> USE_SCOPE_PATHS = createField(DSL.name("use_scope_paths"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.color</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>timeline_graph_section.stroke_color</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, String> STROKE_COLOR = createField(DSL.name("stroke_color"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	/**
	 * The column <code>timeline_graph_section.opacity</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, BigDecimal> OPACITY = createField(DSL.name("opacity"), SQLDataType.DECIMAL(6, 3).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section.dashed</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> DASHED = createField(DSL.name("dashed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.mark</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, TimelineGraphSectionMark> MARK = createField(DSL.name("mark"), SQLDataType.VARCHAR(7).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)).asEnumDataType(TimelineGraphSectionMark.class), this, "");

	/**
	 * The column <code>timeline_graph_section.position_start</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Integer> POSITION_START = createField(DSL.name("position_start"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>timeline_graph_section.position_stop</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Integer> POSITION_STOP = createField(DSL.name("position_stop"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_min</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, BigDecimal> SCALE_MIN = createField(DSL.name("scale_min"), SQLDataType.DECIMAL(18, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_max</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, BigDecimal> SCALE_MAX = createField(DSL.name("scale_max"), SQLDataType.DECIMAL(18, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_decimal</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Integer> SCALE_DECIMAL = createField(DSL.name("scale_decimal"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_mark_interval</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, BigDecimal> SCALE_MARK_INTERVAL = createField(DSL.name("scale_mark_interval"), SQLDataType.DECIMAL(18, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_label_interval</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, BigDecimal> SCALE_LABEL_INTERVAL = createField(DSL.name("scale_label_interval"), SQLDataType.DECIMAL(18, 6).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DECIMAL)), this, "");

	/**
	 * The column <code>timeline_graph_section.scale_position</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, TimelineGraphSectionScalePosition> SCALE_POSITION = createField(DSL.name("scale_position"), SQLDataType.VARCHAR(5).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)).asEnumDataType(TimelineGraphSectionScalePosition.class), this, "");

	/**
	 * The column <code>timeline_graph_section.hidden_legend</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> HIDDEN_LEGEND = createField(DSL.name("hidden_legend"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.hidden</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>timeline_graph_section.label</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>timeline_graph_section.tooltip</code>.
	 */
	public final TableField<TimelineGraphSectionRecord, String> TOOLTIP = createField(DSL.name("tooltip"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	private TimelineGraphSection(Name alias, Table<TimelineGraphSectionRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private TimelineGraphSection(Name alias, Table<TimelineGraphSectionRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>timeline_graph_section</code> table reference
	 */
	public TimelineGraphSection(String alias) {
		this(DSL.name(alias), TIMELINE_GRAPH_SECTION);
	}

	/**
	 * Create an aliased <code>timeline_graph_section</code> table reference
	 */
	public TimelineGraphSection(Name alias) {
		this(alias, TIMELINE_GRAPH_SECTION);
	}

	/**
	 * Create a <code>timeline_graph_section</code> table reference
	 */
	public TimelineGraphSection() {
		this(DSL.name("timeline_graph_section"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<TimelineGraphSectionRecord> getPrimaryKey() {
		return Keys.KEY_TIMELINE_GRAPH_SECTION_PRIMARY;
	}

	@Override
	public List<UniqueKey<TimelineGraphSectionRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_TIMELINE_GRAPH_SECTION_UQ_TIMELINE_GRAPH_SECTION_CODE);
	}

	@Override
	public List<Check<TimelineGraphSectionRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("label"), "json_valid(`label`)", true),
			Internal.createCheck(this, DSL.name("tooltip"), "json_valid(`tooltip`)", true)
		);
	}

	@Override
	public TimelineGraphSection as(String alias) {
		return new TimelineGraphSection(DSL.name(alias), this);
	}

	@Override
	public TimelineGraphSection as(Name alias) {
		return new TimelineGraphSection(alias, this);
	}

	@Override
	public TimelineGraphSection as(Table<?> alias) {
		return new TimelineGraphSection(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSection rename(String name) {
		return new TimelineGraphSection(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSection rename(Name name) {
		return new TimelineGraphSection(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public TimelineGraphSection rename(Table<?> name) {
		return new TimelineGraphSection(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection where(Condition condition) {
		return new TimelineGraphSection(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSection where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSection where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSection where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public TimelineGraphSection where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public TimelineGraphSection whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
