/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Indexes;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.FieldModelValidator.FieldModelValidatorPath;
import ch.rodano.core.model.jooq.tables.Workflow.WorkflowPath;
import ch.rodano.core.model.jooq.tables.WorkflowState.WorkflowStatePath;
import ch.rodano.core.model.jooq.tables.records.ValidatorRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Validator extends TableImpl<ValidatorRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>validator</code>
	 */
	public static final Validator VALIDATOR = new Validator();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ValidatorRecord> getRecordType() {
		return ValidatorRecord.class;
	}

	/**
	 * The column <code>validator.validator_id</code>.
	 */
	public final TableField<ValidatorRecord, UUID> VALIDATOR_ID = createField(DSL.name("validator_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid()"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>validator.project_id</code>.
	 */
	public final TableField<ValidatorRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>validator.code</code>.
	 */
	public final TableField<ValidatorRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

	/**
	 * The column <code>validator.shortname</code>.
	 */
	public final TableField<ValidatorRecord, String> SHORTNAME = createField(DSL.name("shortname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>validator.longname</code>.
	 */
	public final TableField<ValidatorRecord, String> LONGNAME = createField(DSL.name("longname"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>validator.description</code>.
	 */
	public final TableField<ValidatorRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>validator.message</code>.
	 */
	public final TableField<ValidatorRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

	/**
	 * The column <code>validator.required</code>.
	 */
	public final TableField<ValidatorRecord, Boolean> REQUIRED = createField(DSL.name("required"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>validator.is_script</code>.
	 */
	public final TableField<ValidatorRecord, Boolean> IS_SCRIPT = createField(DSL.name("is_script"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>validator.workflow_id</code>.
	 */
	public final TableField<ValidatorRecord, UUID> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>validator.invalid_state_id</code>.
	 */
	public final TableField<ValidatorRecord, UUID> INVALID_STATE_ID = createField(DSL.name("invalid_state_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>validator.valid_state_id</code>.
	 */
	public final TableField<ValidatorRecord, UUID> VALID_STATE_ID = createField(DSL.name("valid_state_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	private Validator(Name alias, Table<ValidatorRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private Validator(Name alias, Table<ValidatorRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>validator</code> table reference
	 */
	public Validator(String alias) {
		this(DSL.name(alias), VALIDATOR);
	}

	/**
	 * Create an aliased <code>validator</code> table reference
	 */
	public Validator(Name alias) {
		this(alias, VALIDATOR);
	}

	/**
	 * Create a <code>validator</code> table reference
	 */
	public Validator() {
		this(DSL.name("validator"), null);
	}

	public <O extends Record> Validator(Table<O> path, ForeignKey<O, ValidatorRecord> childPath, InverseForeignKey<O, ValidatorRecord> parentPath) {
		super(path, childPath, parentPath, VALIDATOR);
	}

	/**
	 * A subtype implementing {@link Path} for simplified path-based joins.
	 */
	public static class ValidatorPath extends Validator implements Path<ValidatorRecord> {

		private static final long serialVersionUID = 1L;
		public <O extends Record> ValidatorPath(Table<O> path, ForeignKey<O, ValidatorRecord> childPath, InverseForeignKey<O, ValidatorRecord> parentPath) {
			super(path, childPath, parentPath);
		}
		private ValidatorPath(Name alias, Table<ValidatorRecord> aliased) {
			super(alias, aliased);
		}

		@Override
		public ValidatorPath as(String alias) {
			return new ValidatorPath(DSL.name(alias), this);
		}

		@Override
		public ValidatorPath as(Name alias) {
			return new ValidatorPath(alias, this);
		}

		@Override
		public ValidatorPath as(Table<?> alias) {
			return new ValidatorPath(alias.getQualifiedName(), this);
		}
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public List<Index> getIndexes() {
		return Arrays.asList(Indexes.VALIDATOR_IDX_VALIDATOR_WORKFLOW);
	}

	@Override
	public UniqueKey<ValidatorRecord> getPrimaryKey() {
		return Keys.KEY_VALIDATOR_PRIMARY;
	}

	@Override
	public List<UniqueKey<ValidatorRecord>> getUniqueKeys() {
		return Arrays.asList(Keys.KEY_VALIDATOR_UQ_VALIDATOR_CODE);
	}

	@Override
	public List<ForeignKey<ValidatorRecord, ?>> getReferences() {
		return Arrays.asList(Keys.FK_VALIDATOR_INVALID_STATE, Keys.FK_VALIDATOR_VALID_STATE, Keys.FK_VALIDATOR_WORKFLOW);
	}

	private transient WorkflowStatePath _fkValidatorInvalidState;

	/**
	 * Get the implicit join path to the <code>workflow_state</code> table, via the
	 * <code>fk_validator_invalid_state</code> key.
	 */
	public WorkflowStatePath fkValidatorInvalidState() {
		if (_fkValidatorInvalidState == null)
			_fkValidatorInvalidState = new WorkflowStatePath(this, Keys.FK_VALIDATOR_INVALID_STATE, null);

		return _fkValidatorInvalidState;
	}

	private transient WorkflowStatePath _fkValidatorValidState;

	/**
	 * Get the implicit join path to the <code>workflow_state</code> table, via the
	 * <code>fk_validator_valid_state</code> key.
	 */
	public WorkflowStatePath fkValidatorValidState() {
		if (_fkValidatorValidState == null)
			_fkValidatorValidState = new WorkflowStatePath(this, Keys.FK_VALIDATOR_VALID_STATE, null);

		return _fkValidatorValidState;
	}

	private transient WorkflowPath _workflow;

	/**
	 * Get the implicit join path to the <code>workflow</code> table.
	 */
	public WorkflowPath workflow() {
		if (_workflow == null)
			_workflow = new WorkflowPath(this, Keys.FK_VALIDATOR_WORKFLOW, null);

		return _workflow;
	}

	private transient FieldModelValidatorPath _fieldModelValidator;

	/**
	 * Get the implicit to-many join path to the <code>field_model_validator</code>
	 * table
	 */
	public FieldModelValidatorPath fieldModelValidator() {
		if (_fieldModelValidator == null)
			_fieldModelValidator = new FieldModelValidatorPath(this, null, Keys.FK_FIELD_MODEL_VALIDATOR_VALIDATOR.getInverseKey());

		return _fieldModelValidator;
	}

	@Override
	public List<Check<ValidatorRecord>> getChecks() {
		return Arrays.asList(
			Internal.createCheck(this, DSL.name("description"), "json_valid(`description`)", true),
			Internal.createCheck(this, DSL.name("longname"), "json_valid(`longname`)", true),
			Internal.createCheck(this, DSL.name("message"), "json_valid(`message`)", true),
			Internal.createCheck(this, DSL.name("shortname"), "json_valid(`shortname`)", true)
		);
	}

	@Override
	public Validator as(String alias) {
		return new Validator(DSL.name(alias), this);
	}

	@Override
	public Validator as(Name alias) {
		return new Validator(alias, this);
	}

	@Override
	public Validator as(Table<?> alias) {
		return new Validator(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Validator rename(String name) {
		return new Validator(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Validator rename(Name name) {
		return new Validator(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Validator rename(Table<?> name) {
		return new Validator(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator where(Condition condition) {
		return new Validator(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Validator where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Validator where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Validator where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public Validator where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public Validator whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
