/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.helpers.configuration.DateConverter;
import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.WorkflowStatusRecord;

import java.time.ZonedDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowStatus extends TableImpl<WorkflowStatusRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>workflow_status</code>
	 */
	public static final WorkflowStatus WORKFLOW_STATUS = new WorkflowStatus();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WorkflowStatusRecord> getRecordType() {
		return WorkflowStatusRecord.class;
	}

	/**
	 * The column <code>workflow_status.pk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> PK = createField(DSL.name("pk"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

	/**
	 * The column <code>workflow_status.project_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>workflow_status.creation_time</code>.
	 */
	public final TableField<WorkflowStatusRecord, ZonedDateTime> CREATION_TIME = createField(DSL.name("creation_time"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp(3)"), SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

	/**
	 * The column <code>workflow_status.last_update_time</code>.
	 */
	public final TableField<WorkflowStatusRecord, ZonedDateTime> LAST_UPDATE_TIME = createField(DSL.name("last_update_time"), SQLDataType.LOCALDATETIME(3).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp(3)"), SQLDataType.LOCALDATETIME)), this, "", new DateConverter());

	/**
	 * The column <code>workflow_status.deleted</code>.
	 */
	public final TableField<WorkflowStatusRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BOOLEAN)), this, "");

	/**
	 * The column <code>workflow_status.scope_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> SCOPE_FK = createField(DSL.name("scope_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.event_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> EVENT_FK = createField(DSL.name("event_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.form_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> FORM_FK = createField(DSL.name("form_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.field_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> FIELD_FK = createField(DSL.name("field_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.user_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> USER_FK = createField(DSL.name("user_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.robot_fk</code>.
	 */
	public final TableField<WorkflowStatusRecord, Long> ROBOT_FK = createField(DSL.name("robot_fk"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

	/**
	 * The column <code>workflow_status.profile_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> PROFILE_ID = createField(DSL.name("profile_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>workflow_status.workflow_state_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> WORKFLOW_STATE_ID = createField(DSL.name("workflow_state_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>workflow_status.workflow_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> WORKFLOW_ID = createField(DSL.name("workflow_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>workflow_status.workflow_action_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> WORKFLOW_ACTION_ID = createField(DSL.name("workflow_action_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>workflow_status.validator_id</code>.
	 */
	public final TableField<WorkflowStatusRecord, UUID> VALIDATOR_ID = createField(DSL.name("validator_id"), SQLDataType.UUID.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.UUID)), this, "");

	/**
	 * The column <code>workflow_status.trigger_message</code>.
	 */
	public final TableField<WorkflowStatusRecord, String> TRIGGER_MESSAGE = createField(DSL.name("trigger_message"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

	private WorkflowStatus(Name alias, Table<WorkflowStatusRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private WorkflowStatus(Name alias, Table<WorkflowStatusRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>workflow_status</code> table reference
	 */
	public WorkflowStatus(String alias) {
		this(DSL.name(alias), WORKFLOW_STATUS);
	}

	/**
	 * Create an aliased <code>workflow_status</code> table reference
	 */
	public WorkflowStatus(Name alias) {
		this(alias, WORKFLOW_STATUS);
	}

	/**
	 * Create a <code>workflow_status</code> table reference
	 */
	public WorkflowStatus() {
		this(DSL.name("workflow_status"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public Identity<WorkflowStatusRecord, Long> getIdentity() {
		return (Identity<WorkflowStatusRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<WorkflowStatusRecord> getPrimaryKey() {
		return Keys.KEY_WORKFLOW_STATUS_PRIMARY;
	}

	@Override
	public WorkflowStatus as(String alias) {
		return new WorkflowStatus(DSL.name(alias), this);
	}

	@Override
	public WorkflowStatus as(Name alias) {
		return new WorkflowStatus(alias, this);
	}

	@Override
	public WorkflowStatus as(Table<?> alias) {
		return new WorkflowStatus(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowStatus rename(String name) {
		return new WorkflowStatus(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowStatus rename(Name name) {
		return new WorkflowStatus(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowStatus rename(Table<?> name) {
		return new WorkflowStatus(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus where(Condition condition) {
		return new WorkflowStatus(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowStatus where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowStatus where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowStatus where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowStatus where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowStatus whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
