/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables;


import ch.rodano.core.model.jooq.DefaultSchema;
import ch.rodano.core.model.jooq.Keys;
import ch.rodano.core.model.jooq.tables.records.WorkflowSummaryFilterEventModelRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowSummaryFilterEventModel extends TableImpl<WorkflowSummaryFilterEventModelRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * The reference instance of <code>workflow_summary_filter_event_model</code>
	 */
	public static final WorkflowSummaryFilterEventModel WORKFLOW_SUMMARY_FILTER_EVENT_MODEL = new WorkflowSummaryFilterEventModel();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WorkflowSummaryFilterEventModelRecord> getRecordType() {
		return WorkflowSummaryFilterEventModelRecord.class;
	}

	/**
	 * The column <code>workflow_summary_filter_event_model.project_id</code>.
	 */
	public final TableField<WorkflowSummaryFilterEventModelRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column
	 * <code>workflow_summary_filter_event_model.workflow_summary_id</code>.
	 */
	public final TableField<WorkflowSummaryFilterEventModelRecord, UUID> WORKFLOW_SUMMARY_ID = createField(DSL.name("workflow_summary_id"), SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>workflow_summary_filter_event_model.event_model_id</code>.
	 */
	public final TableField<WorkflowSummaryFilterEventModelRecord, UUID> EVENT_MODEL_ID = createField(DSL.name("event_model_id"), SQLDataType.UUID.nullable(false), this, "");

	private WorkflowSummaryFilterEventModel(Name alias, Table<WorkflowSummaryFilterEventModelRecord> aliased) {
		this(alias, aliased, (Field<?>[]) null, null);
	}

	private WorkflowSummaryFilterEventModel(Name alias, Table<WorkflowSummaryFilterEventModelRecord> aliased, Field<?>[] parameters, Condition where) {
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
	}

	/**
	 * Create an aliased <code>workflow_summary_filter_event_model</code> table
	 * reference
	 */
	public WorkflowSummaryFilterEventModel(String alias) {
		this(DSL.name(alias), WORKFLOW_SUMMARY_FILTER_EVENT_MODEL);
	}

	/**
	 * Create an aliased <code>workflow_summary_filter_event_model</code> table
	 * reference
	 */
	public WorkflowSummaryFilterEventModel(Name alias) {
		this(alias, WORKFLOW_SUMMARY_FILTER_EVENT_MODEL);
	}

	/**
	 * Create a <code>workflow_summary_filter_event_model</code> table reference
	 */
	public WorkflowSummaryFilterEventModel() {
		this(DSL.name("workflow_summary_filter_event_model"), null);
	}

	@Override
	public Schema getSchema() {
		return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
	}

	@Override
	public UniqueKey<WorkflowSummaryFilterEventModelRecord> getPrimaryKey() {
		return Keys.KEY_WORKFLOW_SUMMARY_FILTER_EVENT_MODEL_PRIMARY;
	}

	@Override
	public WorkflowSummaryFilterEventModel as(String alias) {
		return new WorkflowSummaryFilterEventModel(DSL.name(alias), this);
	}

	@Override
	public WorkflowSummaryFilterEventModel as(Name alias) {
		return new WorkflowSummaryFilterEventModel(alias, this);
	}

	@Override
	public WorkflowSummaryFilterEventModel as(Table<?> alias) {
		return new WorkflowSummaryFilterEventModel(alias.getQualifiedName(), this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel rename(String name) {
		return new WorkflowSummaryFilterEventModel(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel rename(Name name) {
		return new WorkflowSummaryFilterEventModel(name, null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel rename(Table<?> name) {
		return new WorkflowSummaryFilterEventModel(name.getQualifiedName(), null);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel where(Condition condition) {
		return new WorkflowSummaryFilterEventModel(getQualifiedName(), aliased() ? this : null, null, condition);
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel where(Collection<? extends Condition> conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel where(Condition... conditions) {
		return where(DSL.and(conditions));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel where(Field<Boolean> condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowSummaryFilterEventModel where(SQL condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowSummaryFilterEventModel where(@Stringly.SQL String condition) {
		return where(DSL.condition(condition));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowSummaryFilterEventModel where(@Stringly.SQL String condition, Object... binds) {
		return where(DSL.condition(condition, binds));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	@PlainSQL
	public WorkflowSummaryFilterEventModel where(@Stringly.SQL String condition, QueryPart... parts) {
		return where(DSL.condition(condition, parts));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel whereExists(Select<?> select) {
		return where(DSL.exists(select));
	}

	/**
	 * Create an inline derived table from this table
	 */
	@Override
	public WorkflowSummaryFilterEventModel whereNotExists(Select<?> select) {
		return where(DSL.notExists(select));
	}
}
