### Start import job with defaults from application.yml
POST http://localhost:8080/api/batch/import
Content-Type: application/json

{
  "projectId": "TEST"
}

### Start import job with overrides
POST http://localhost:8080/api/batch/import
Content-Type: application/json

{
  "projectId": "TEST_FARIS",
  "config": "classpath:config/config2.json",
  "dbUrl": "jdbc:mariadb://localhost:3306/rodano",
  "dbUser": "root",
  "dbPassword": "root"
}

### Get status of job execution with id 1
GET http://localhost:8080/api/batch/execution/1

### Stop execution with id 1
POST http://localhost:8080/api/batch/execution/1/stop

### Initialize project runtime data
POST http://localhost:8080/administration/projects/initialize
Content-Type: application/json

{
  "projectCode": "TEST",
  "adminName": "Test User",
  "adminEmail": "test@rodano.ch",
  "adminPassword": "Password1!",
  "withDemoUsers": true,
  "withDemoData": true
}