/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.ChartColor;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChartColorRecord extends UpdatableRecordImpl<ChartColorRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>chart_color.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>chart_color.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>chart_color.chart_id</code>.
	 */
	public void setChartId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>chart_color.chart_id</code>.
	 */
	public UUID getChartId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>chart_color.color</code>.
	 */
	public void setColor(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>chart_color.color</code>.
	 */
	public String getColor() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>chart_color.sort_order</code>.
	 */
	public void setSortOrder(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>chart_color.sort_order</code>.
	 */
	public Integer getSortOrder() {
		return (Integer) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChartColorRecord
	 */
	public ChartColorRecord() {
		super(ChartColor.CHART_COLOR);
	}

	/**
	 * Create a detached, initialised ChartColorRecord
	 */
	public ChartColorRecord(UUID projectId, UUID chartId, String color, Integer sortOrder) {
		super(ChartColor.CHART_COLOR);

		setProjectId(projectId);
		setChartId(chartId);
		setColor(color);
		setSortOrder(sortOrder);
		resetChangedOnNotNull();
	}
}
