/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.DatasetModel;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DatasetModelRecord extends UpdatableRecordImpl<DatasetModelRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>dataset_model.dataset_model_id</code>.
	 */
	public void setDatasetModelId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>dataset_model.dataset_model_id</code>.
	 */
	public UUID getDatasetModelId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>dataset_model.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>dataset_model.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>dataset_model.code</code>.
	 */
	public void setCode(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>dataset_model.code</code>.
	 */
	public String getCode() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>dataset_model.shortname</code>.
	 */
	public void setShortname(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>dataset_model.shortname</code>.
	 */
	public String getShortname() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>dataset_model.longname</code>.
	 */
	public void setLongname(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>dataset_model.longname</code>.
	 */
	public String getLongname() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>dataset_model.description</code>.
	 */
	public void setDescription(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>dataset_model.description</code>.
	 */
	public String getDescription() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>dataset_model.multiple</code>.
	 */
	public void setMultiple(Boolean value) {
		set(6, value);
	}

	/**
	 * Getter for <code>dataset_model.multiple</code>.
	 */
	public Boolean getMultiple() {
		return (Boolean) get(6);
	}

	/**
	 * Setter for <code>dataset_model.master</code>.
	 */
	public void setMaster(Boolean value) {
		set(7, value);
	}

	/**
	 * Getter for <code>dataset_model.master</code>.
	 */
	public Boolean getMaster() {
		return (Boolean) get(7);
	}

	/**
	 * Setter for <code>dataset_model.exportable</code>.
	 */
	public void setExportable(Boolean value) {
		set(8, value);
	}

	/**
	 * Getter for <code>dataset_model.exportable</code>.
	 */
	public Boolean getExportable() {
		return (Boolean) get(8);
	}

	/**
	 * Setter for <code>dataset_model.export_order</code>.
	 */
	public void setExportOrder(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>dataset_model.export_order</code>.
	 */
	public Integer getExportOrder() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>dataset_model.family</code>.
	 */
	public void setFamily(String value) {
		set(10, value);
	}

	/**
	 * Getter for <code>dataset_model.family</code>.
	 */
	public String getFamily() {
		return (String) get(10);
	}

	/**
	 * Setter for <code>dataset_model.collapsed_label_pattern</code>.
	 */
	public void setCollapsedLabelPattern(String value) {
		set(11, value);
	}

	/**
	 * Getter for <code>dataset_model.collapsed_label_pattern</code>.
	 */
	public String getCollapsedLabelPattern() {
		return (String) get(11);
	}

	/**
	 * Setter for <code>dataset_model.expanded_label_pattern</code>.
	 */
	public void setExpandedLabelPattern(String value) {
		set(12, value);
	}

	/**
	 * Getter for <code>dataset_model.expanded_label_pattern</code>.
	 */
	public String getExpandedLabelPattern() {
		return (String) get(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<UUID, UUID> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DatasetModelRecord
	 */
	public DatasetModelRecord() {
		super(DatasetModel.DATASET_MODEL);
	}

	/**
	 * Create a detached, initialised DatasetModelRecord
	 */
	public DatasetModelRecord(UUID datasetModelId, UUID projectId, String code, String shortname, String longname, String description, Boolean multiple, Boolean master, Boolean exportable, Integer exportOrder, String family, String collapsedLabelPattern, String expandedLabelPattern) {
		super(DatasetModel.DATASET_MODEL);

		setDatasetModelId(datasetModelId);
		setProjectId(projectId);
		setCode(code);
		setShortname(shortname);
		setLongname(longname);
		setDescription(description);
		setMultiple(multiple);
		setMaster(master);
		setExportable(exportable);
		setExportOrder(exportOrder);
		setFamily(family);
		setCollapsedLabelPattern(collapsedLabelPattern);
		setExpandedLabelPattern(expandedLabelPattern);
		resetChangedOnNotNull();
	}
}
