/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.EventModelBlockedEvent;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventModelBlockedEventRecord extends UpdatableRecordImpl<EventModelBlockedEventRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>event_model_blocked_event.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>event_model_blocked_event.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>event_model_blocked_event.event_model_id</code>.
	 */
	public void setEventModelId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>event_model_blocked_event.event_model_id</code>.
	 */
	public UUID getEventModelId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>event_model_blocked_event.blocked_event_model_id</code>.
	 */
	public void setBlockedEventModelId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>event_model_blocked_event.blocked_event_model_id</code>.
	 */
	public UUID getBlockedEventModelId() {
		return (UUID) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventModelBlockedEventRecord
	 */
	public EventModelBlockedEventRecord() {
		super(EventModelBlockedEvent.EVENT_MODEL_BLOCKED_EVENT);
	}

	/**
	 * Create a detached, initialised EventModelBlockedEventRecord
	 */
	public EventModelBlockedEventRecord(UUID projectId, UUID eventModelId, UUID blockedEventModelId) {
		super(EventModelBlockedEvent.EVENT_MODEL_BLOCKED_EVENT);

		setProjectId(projectId);
		setEventModelId(eventModelId);
		setBlockedEventModelId(blockedEventModelId);
		resetChangedOnNotNull();
	}
}
