/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.EventModelWorkflow;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventModelWorkflowRecord extends UpdatableRecordImpl<EventModelWorkflowRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>event_model_workflow.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>event_model_workflow.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>event_model_workflow.event_model_id</code>.
	 */
	public void setEventModelId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>event_model_workflow.event_model_id</code>.
	 */
	public UUID getEventModelId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>event_model_workflow.workflow_id</code>.
	 */
	public void setWorkflowId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>event_model_workflow.workflow_id</code>.
	 */
	public UUID getWorkflowId() {
		return (UUID) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventModelWorkflowRecord
	 */
	public EventModelWorkflowRecord() {
		super(EventModelWorkflow.EVENT_MODEL_WORKFLOW);
	}

	/**
	 * Create a detached, initialised EventModelWorkflowRecord
	 */
	public EventModelWorkflowRecord(UUID projectId, UUID eventModelId, UUID workflowId) {
		super(EventModelWorkflow.EVENT_MODEL_WORKFLOW);

		setProjectId(projectId);
		setEventModelId(eventModelId);
		setWorkflowId(workflowId);
		resetChangedOnNotNull();
	}
}
