/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.FormCellVisibilityCriteriaValue;

import java.util.UUID;

import org.jooq.Record4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FormCellVisibilityCriteriaValueRecord extends UpdatableRecordImpl<FormCellVisibilityCriteriaValueRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>form_cell_visibility_criteria_value.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>form_cell_visibility_criteria_value.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for
	 * <code>form_cell_visibility_criteria_value.form_layout_cell_id</code>.
	 */
	public void setFormLayoutCellId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for
	 * <code>form_cell_visibility_criteria_value.form_layout_cell_id</code>.
	 */
	public UUID getFormLayoutCellId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for
	 * <code>form_cell_visibility_criteria_value.form_cell_visible_criteria_id</code>.
	 */
	public void setFormCellVisibleCriteriaId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for
	 * <code>form_cell_visibility_criteria_value.form_cell_visible_criteria_id</code>.
	 */
	public UUID getFormCellVisibleCriteriaId() {
		return (UUID) get(2);
	}

	/**
	 * Setter for <code>form_cell_visibility_criteria_value.line_order</code>.
	 */
	public void setLineOrder(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>form_cell_visibility_criteria_value.line_order</code>.
	 */
	public Integer getLineOrder() {
		return (Integer) get(3);
	}

	/**
	 * Setter for
	 * <code>form_cell_visibility_criteria_value.possible_value_id</code>.
	 */
	public void setPossibleValueId(UUID value) {
		set(4, value);
	}

	/**
	 * Getter for
	 * <code>form_cell_visibility_criteria_value.possible_value_id</code>.
	 */
	public UUID getPossibleValueId() {
		return (UUID) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record4<UUID, UUID, UUID, UUID> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FormCellVisibilityCriteriaValueRecord
	 */
	public FormCellVisibilityCriteriaValueRecord() {
		super(FormCellVisibilityCriteriaValue.FORM_CELL_VISIBILITY_CRITERIA_VALUE);
	}

	/**
	 * Create a detached, initialised FormCellVisibilityCriteriaValueRecord
	 */
	public FormCellVisibilityCriteriaValueRecord(UUID projectId, UUID formLayoutCellId, UUID formCellVisibleCriteriaId, Integer lineOrder, UUID possibleValueId) {
		super(FormCellVisibilityCriteriaValue.FORM_CELL_VISIBILITY_CRITERIA_VALUE);

		setProjectId(projectId);
		setFormLayoutCellId(formLayoutCellId);
		setFormCellVisibleCriteriaId(formCellVisibleCriteriaId);
		setLineOrder(lineOrder);
		setPossibleValueId(possibleValueId);
		resetChangedOnNotNull();
	}
}
