/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.Mail;
import ch.rodano.core.model.mail.MailOrigin;
import ch.rodano.core.model.mail.MailStatus;

import java.time.ZonedDateTime;
import java.util.Set;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MailRecord extends UpdatableRecordImpl<MailRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>mail.pk</code>.
	 */
	public void setPk(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>mail.pk</code>.
	 */
	public Long getPk() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>mail.creation_time</code>.
	 */
	public void setCreationTime(ZonedDateTime value) {
		set(1, value);
	}

	/**
	 * Getter for <code>mail.creation_time</code>.
	 */
	public ZonedDateTime getCreationTime() {
		return (ZonedDateTime) get(1);
	}

	/**
	 * Setter for <code>mail.last_update_time</code>.
	 */
	public void setLastUpdateTime(ZonedDateTime value) {
		set(2, value);
	}

	/**
	 * Getter for <code>mail.last_update_time</code>.
	 */
	public ZonedDateTime getLastUpdateTime() {
		return (ZonedDateTime) get(2);
	}

	/**
	 * Setter for <code>mail.attempts</code>.
	 */
	public void setAttempts(Integer value) {
		set(3, value);
	}

	/**
	 * Getter for <code>mail.attempts</code>.
	 */
	public Integer getAttempts() {
		return (Integer) get(3);
	}

	/**
	 * Setter for <code>mail.status</code>.
	 */
	public void setStatus(MailStatus value) {
		set(4, value);
	}

	/**
	 * Getter for <code>mail.status</code>.
	 */
	public MailStatus getStatus() {
		return (MailStatus) get(4);
	}

	/**
	 * Setter for <code>mail.error</code>.
	 */
	public void setError(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>mail.error</code>.
	 */
	public String getError() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>mail.sent_time</code>.
	 */
	public void setSentTime(ZonedDateTime value) {
		set(6, value);
	}

	/**
	 * Getter for <code>mail.sent_time</code>.
	 */
	public ZonedDateTime getSentTime() {
		return (ZonedDateTime) get(6);
	}

	/**
	 * Setter for <code>mail.origin</code>.
	 */
	public void setOrigin(MailOrigin value) {
		set(7, value);
	}

	/**
	 * Getter for <code>mail.origin</code>.
	 */
	public MailOrigin getOrigin() {
		return (MailOrigin) get(7);
	}

	/**
	 * Setter for <code>mail.intent</code>.
	 */
	public void setIntent(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>mail.intent</code>.
	 */
	public String getIntent() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>mail.sender</code>.
	 */
	public void setSender(String value) {
		set(9, value);
	}

	/**
	 * Getter for <code>mail.sender</code>.
	 */
	public String getSender() {
		return (String) get(9);
	}

	/**
	 * Setter for <code>mail.recipients</code>.
	 */
	public void setRecipients(Set value) {
		set(10, value);
	}

	/**
	 * Getter for <code>mail.recipients</code>.
	 */
	public Set getRecipients() {
		return (Set) get(10);
	}

	/**
	 * Setter for <code>mail.reply_to</code>.
	 */
	public void setReplyTo(String value) {
		set(11, value);
	}

	/**
	 * Getter for <code>mail.reply_to</code>.
	 */
	public String getReplyTo() {
		return (String) get(11);
	}

	/**
	 * Setter for <code>mail.subject</code>.
	 */
	public void setSubject(String value) {
		set(12, value);
	}

	/**
	 * Getter for <code>mail.subject</code>.
	 */
	public String getSubject() {
		return (String) get(12);
	}

	/**
	 * Setter for <code>mail.text_body</code>.
	 */
	public void setTextBody(String value) {
		set(13, value);
	}

	/**
	 * Getter for <code>mail.text_body</code>.
	 */
	public String getTextBody() {
		return (String) get(13);
	}

	/**
	 * Setter for <code>mail.html_body</code>.
	 */
	public void setHtmlBody(String value) {
		set(14, value);
	}

	/**
	 * Getter for <code>mail.html_body</code>.
	 */
	public String getHtmlBody() {
		return (String) get(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MailRecord
	 */
	public MailRecord() {
		super(Mail.MAIL);
	}

	/**
	 * Create a detached, initialised MailRecord
	 */
	public MailRecord(Long pk, ZonedDateTime creationTime, ZonedDateTime lastUpdateTime, Integer attempts, MailStatus status, String error, ZonedDateTime sentTime, MailOrigin origin, String intent, String sender, Set recipients, String replyTo, String subject, String textBody, String htmlBody) {
		super(Mail.MAIL);

		setPk(pk);
		setCreationTime(creationTime);
		setLastUpdateTime(lastUpdateTime);
		setAttempts(attempts);
		setStatus(status);
		setError(error);
		setSentTime(sentTime);
		setOrigin(origin);
		setIntent(intent);
		setSender(sender);
		setRecipients(recipients);
		setReplyTo(replyTo);
		setSubject(subject);
		setTextBody(textBody);
		setHtmlBody(htmlBody);
		resetChangedOnNotNull();
	}
}
