/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.MenuLayoutSectionWidgetParameter;

import java.util.UUID;

import org.jooq.Record4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MenuLayoutSectionWidgetParameterRecord extends UpdatableRecordImpl<MenuLayoutSectionWidgetParameterRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.menu_id</code>.
	 */
	public void setMenuId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.menu_id</code>.
	 */
	public UUID getMenuId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for
	 * <code>menu_layout_section_widget_parameter.menu_section_id</code>.
	 */
	public void setMenuSectionId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for
	 * <code>menu_layout_section_widget_parameter.menu_section_id</code>.
	 */
	public UUID getMenuSectionId() {
		return (UUID) get(2);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.menu_widget_id</code>.
	 */
	public void setMenuWidgetId(UUID value) {
		set(3, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.menu_widget_id</code>.
	 */
	public UUID getMenuWidgetId() {
		return (UUID) get(3);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.widget_order</code>.
	 */
	public void setWidgetOrder(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.widget_order</code>.
	 */
	public Integer getWidgetOrder() {
		return (Integer) get(4);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.type</code>.
	 */
	public void setType(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.type</code>.
	 */
	public String getType() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.title</code>.
	 */
	public void setTitle(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.title</code>.
	 */
	public String getTitle() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.width</code>.
	 */
	public void setWidth(Integer value) {
		set(7, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.width</code>.
	 */
	public Integer getWidth() {
		return (Integer) get(7);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.scope_model_id</code>.
	 */
	public void setScopeModelId(UUID value) {
		set(8, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.scope_model_id</code>.
	 */
	public UUID getScopeModelId() {
		return (UUID) get(8);
	}

	/**
	 * Setter for
	 * <code>menu_layout_section_widget_parameter.workflow_widget_id</code>.
	 */
	public void setWorkflowWidgetId(UUID value) {
		set(9, value);
	}

	/**
	 * Getter for
	 * <code>menu_layout_section_widget_parameter.workflow_widget_id</code>.
	 */
	public UUID getWorkflowWidgetId() {
		return (UUID) get(9);
	}

	/**
	 * Setter for
	 * <code>menu_layout_section_widget_parameter.workflow_summary_id</code>.
	 */
	public void setWorkflowSummaryId(UUID value) {
		set(10, value);
	}

	/**
	 * Getter for
	 * <code>menu_layout_section_widget_parameter.workflow_summary_id</code>.
	 */
	public UUID getWorkflowSummaryId() {
		return (UUID) get(10);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.chart_id</code>.
	 */
	public void setChartId(UUID value) {
		set(11, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.chart_id</code>.
	 */
	public UUID getChartId() {
		return (UUID) get(11);
	}

	/**
	 * Setter for <code>menu_layout_section_widget_parameter.category_id</code>.
	 */
	public void setCategoryId(UUID value) {
		set(12, value);
	}

	/**
	 * Getter for <code>menu_layout_section_widget_parameter.category_id</code>.
	 */
	public UUID getCategoryId() {
		return (UUID) get(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record4<UUID, UUID, UUID, UUID> key() {
		return (Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MenuLayoutSectionWidgetParameterRecord
	 */
	public MenuLayoutSectionWidgetParameterRecord() {
		super(MenuLayoutSectionWidgetParameter.MENU_LAYOUT_SECTION_WIDGET_PARAMETER);
	}

	/**
	 * Create a detached, initialised MenuLayoutSectionWidgetParameterRecord
	 */
	public MenuLayoutSectionWidgetParameterRecord(UUID projectId, UUID menuId, UUID menuSectionId, UUID menuWidgetId, Integer widgetOrder, String type, String title, Integer width, UUID scopeModelId, UUID workflowWidgetId, UUID workflowSummaryId, UUID chartId, UUID categoryId) {
		super(MenuLayoutSectionWidgetParameter.MENU_LAYOUT_SECTION_WIDGET_PARAMETER);

		setProjectId(projectId);
		setMenuId(menuId);
		setMenuSectionId(menuSectionId);
		setMenuWidgetId(menuWidgetId);
		setWidgetOrder(widgetOrder);
		setType(type);
		setTitle(title);
		setWidth(width);
		setScopeModelId(scopeModelId);
		setWorkflowWidgetId(workflowWidgetId);
		setWorkflowSummaryId(workflowSummaryId);
		setChartId(chartId);
		setCategoryId(categoryId);
		resetChangedOnNotNull();
	}
}
