/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.MenuAction;

import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MenuActionRecord extends UpdatableRecordImpl<MenuActionRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>menu_action.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>menu_action.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>menu_action.menu_id</code>.
	 */
	public void setMenuId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>menu_action.menu_id</code>.
	 */
	public UUID getMenuId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>menu_action.page</code>.
	 */
	public void setPage(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>menu_action.page</code>.
	 */
	public String getPage() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>menu_action.context</code>.
	 */
	public void setContext(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>menu_action.context</code>.
	 */
	public String getContext() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>menu_action.params</code>.
	 */
	public void setParams(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>menu_action.params</code>.
	 */
	public String getParams() {
		return (String) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record2<UUID, UUID> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MenuActionRecord
	 */
	public MenuActionRecord() {
		super(MenuAction.MENU_ACTION);
	}

	/**
	 * Create a detached, initialised MenuActionRecord
	 */
	public MenuActionRecord(UUID projectId, UUID menuId, String page, String context, String params) {
		super(MenuAction.MENU_ACTION);

		setProjectId(projectId);
		setMenuId(menuId);
		setPage(page);
		setContext(context);
		setParams(params);
		resetChangedOnNotNull();
	}
}
