/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.ProfileCategoryGrants;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProfileCategoryGrantsRecord extends UpdatableRecordImpl<ProfileCategoryGrantsRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>profile_category_grants.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>profile_category_grants.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>profile_category_grants.profile_id</code>.
	 */
	public void setProfileId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>profile_category_grants.profile_id</code>.
	 */
	public UUID getProfileId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>profile_category_grants.category_id</code>.
	 */
	public void setCategoryId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>profile_category_grants.category_id</code>.
	 */
	public UUID getCategoryId() {
		return (UUID) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProfileCategoryGrantsRecord
	 */
	public ProfileCategoryGrantsRecord() {
		super(ProfileCategoryGrants.PROFILE_CATEGORY_GRANTS);
	}

	/**
	 * Create a detached, initialised ProfileCategoryGrantsRecord
	 */
	public ProfileCategoryGrantsRecord(UUID projectId, UUID profileId, UUID categoryId) {
		super(ProfileCategoryGrants.PROFILE_CATEGORY_GRANTS);

		setProjectId(projectId);
		setProfileId(profileId);
		setCategoryId(categoryId);
		resetChangedOnNotNull();
	}
}
