/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.RuleCriterionValue;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuleCriterionValueRecord extends UpdatableRecordImpl<RuleCriterionValueRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>rule_criterion_value.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>rule_criterion_value.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>rule_criterion_value.criterion_id</code>.
	 */
	public void setCriterionId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>rule_criterion_value.criterion_id</code>.
	 */
	public UUID getCriterionId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>rule_criterion_value.value_order</code>.
	 */
	public void setValueOrder(Integer value) {
		set(2, value);
	}

	/**
	 * Getter for <code>rule_criterion_value.value_order</code>.
	 */
	public Integer getValueOrder() {
		return (Integer) get(2);
	}

	/**
	 * Setter for <code>rule_criterion_value.value_text</code>.
	 */
	public void setValueText(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>rule_criterion_value.value_text</code>.
	 */
	public String getValueText() {
		return (String) get(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, Integer> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RuleCriterionValueRecord
	 */
	public RuleCriterionValueRecord() {
		super(RuleCriterionValue.RULE_CRITERION_VALUE);
	}

	/**
	 * Create a detached, initialised RuleCriterionValueRecord
	 */
	public RuleCriterionValueRecord(UUID projectId, UUID criterionId, Integer valueOrder, String valueText) {
		super(RuleCriterionValue.RULE_CRITERION_VALUE);

		setProjectId(projectId);
		setCriterionId(criterionId);
		setValueOrder(valueOrder);
		setValueText(valueText);
		resetChangedOnNotNull();
	}
}
