/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.ScopeModelParent;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ScopeModelParentRecord extends UpdatableRecordImpl<ScopeModelParentRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>scope_model_parent.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>scope_model_parent.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>scope_model_parent.child_scope_model_id</code>.
	 */
	public void setChildScopeModelId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>scope_model_parent.child_scope_model_id</code>.
	 */
	public UUID getChildScopeModelId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>scope_model_parent.parent_scope_model_id</code>.
	 */
	public void setParentScopeModelId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>scope_model_parent.parent_scope_model_id</code>.
	 */
	public UUID getParentScopeModelId() {
		return (UUID) get(2);
	}

	/**
	 * Setter for <code>scope_model_parent.is_default</code>.
	 */
	public void setIsDefault(Boolean value) {
		set(3, value);
	}

	/**
	 * Getter for <code>scope_model_parent.is_default</code>.
	 */
	public Boolean getIsDefault() {
		return (Boolean) get(3);
	}

	/**
	 * Setter for <code>scope_model_parent.parent_order</code>.
	 */
	public void setParentOrder(Integer value) {
		set(4, value);
	}

	/**
	 * Getter for <code>scope_model_parent.parent_order</code>.
	 */
	public Integer getParentOrder() {
		return (Integer) get(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScopeModelParentRecord
	 */
	public ScopeModelParentRecord() {
		super(ScopeModelParent.SCOPE_MODEL_PARENT);
	}

	/**
	 * Create a detached, initialised ScopeModelParentRecord
	 */
	public ScopeModelParentRecord(UUID projectId, UUID childScopeModelId, UUID parentScopeModelId, Boolean isDefault, Integer parentOrder) {
		super(ScopeModelParent.SCOPE_MODEL_PARENT);

		setProjectId(projectId);
		setChildScopeModelId(childScopeModelId);
		setParentScopeModelId(parentScopeModelId);
		setIsDefault(isDefault);
		setParentOrder(parentOrder);
		resetChangedOnNotNull();
	}
}
