/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.WorkflowWidgetColumn;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowWidgetColumnRecord extends UpdatableRecordImpl<WorkflowWidgetColumnRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>workflow_widget_column.workflow_widget_column_id</code>.
	 */
	public void setWorkflowWidgetColumnId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.workflow_widget_column_id</code>.
	 */
	public UUID getWorkflowWidgetColumnId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>workflow_widget_column.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>workflow_widget_column.workflow_widget_id</code>.
	 */
	public void setWorkflowWidgetId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.workflow_widget_id</code>.
	 */
	public UUID getWorkflowWidgetId() {
		return (UUID) get(2);
	}

	/**
	 * Setter for <code>workflow_widget_column.code</code>.
	 */
	public void setCode(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.code</code>.
	 */
	public String getCode() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>workflow_widget_column.type</code>.
	 */
	public void setType(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.type</code>.
	 */
	public String getType() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>workflow_widget_column.width</code>.
	 */
	public void setWidth(Integer value) {
		set(5, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.width</code>.
	 */
	public Integer getWidth() {
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>workflow_widget_column.shortname</code>.
	 */
	public void setShortname(String value) {
		set(6, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.shortname</code>.
	 */
	public String getShortname() {
		return (String) get(6);
	}

	/**
	 * Setter for <code>workflow_widget_column.longname</code>.
	 */
	public void setLongname(String value) {
		set(7, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.longname</code>.
	 */
	public String getLongname() {
		return (String) get(7);
	}

	/**
	 * Setter for <code>workflow_widget_column.description</code>.
	 */
	public void setDescription(String value) {
		set(8, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.description</code>.
	 */
	public String getDescription() {
		return (String) get(8);
	}

	/**
	 * Setter for <code>workflow_widget_column.sort_order</code>.
	 */
	public void setSortOrder(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>workflow_widget_column.sort_order</code>.
	 */
	public Integer getSortOrder() {
		return (Integer) get(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkflowWidgetColumnRecord
	 */
	public WorkflowWidgetColumnRecord() {
		super(WorkflowWidgetColumn.WORKFLOW_WIDGET_COLUMN);
	}

	/**
	 * Create a detached, initialised WorkflowWidgetColumnRecord
	 */
	public WorkflowWidgetColumnRecord(UUID workflowWidgetColumnId, UUID projectId, UUID workflowWidgetId, String code, String type, Integer width, String shortname, String longname, String description, Integer sortOrder) {
		super(WorkflowWidgetColumn.WORKFLOW_WIDGET_COLUMN);

		setWorkflowWidgetColumnId(workflowWidgetColumnId);
		setProjectId(projectId);
		setWorkflowWidgetId(workflowWidgetId);
		setCode(code);
		setType(type);
		setWidth(width);
		setShortname(shortname);
		setLongname(longname);
		setDescription(description);
		setSortOrder(sortOrder);
		resetChangedOnNotNull();
	}
}
