/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq.tables.records;


import ch.rodano.core.model.jooq.tables.WorkflowSummaryWorkflow;

import java.util.UUID;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorkflowSummaryWorkflowRecord extends UpdatableRecordImpl<WorkflowSummaryWorkflowRecord> {

	private static final long serialVersionUID = 1L;

	/**
	 * Setter for <code>workflow_summary_workflow.project_id</code>.
	 */
	public void setProjectId(UUID value) {
		set(0, value);
	}

	/**
	 * Getter for <code>workflow_summary_workflow.project_id</code>.
	 */
	public UUID getProjectId() {
		return (UUID) get(0);
	}

	/**
	 * Setter for <code>workflow_summary_workflow.workflow_summary_id</code>.
	 */
	public void setWorkflowSummaryId(UUID value) {
		set(1, value);
	}

	/**
	 * Getter for <code>workflow_summary_workflow.workflow_summary_id</code>.
	 */
	public UUID getWorkflowSummaryId() {
		return (UUID) get(1);
	}

	/**
	 * Setter for <code>workflow_summary_workflow.workflow_id</code>.
	 */
	public void setWorkflowId(UUID value) {
		set(2, value);
	}

	/**
	 * Getter for <code>workflow_summary_workflow.workflow_id</code>.
	 */
	public UUID getWorkflowId() {
		return (UUID) get(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	@Override
	public Record3<UUID, UUID, UUID> key() {
		return (Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkflowSummaryWorkflowRecord
	 */
	public WorkflowSummaryWorkflowRecord() {
		super(WorkflowSummaryWorkflow.WORKFLOW_SUMMARY_WORKFLOW);
	}

	/**
	 * Create a detached, initialised WorkflowSummaryWorkflowRecord
	 */
	public WorkflowSummaryWorkflowRecord(UUID projectId, UUID workflowSummaryId, UUID workflowId) {
		super(WorkflowSummaryWorkflow.WORKFLOW_SUMMARY_WORKFLOW);

		setProjectId(projectId);
		setWorkflowSummaryId(workflowSummaryId);
		setWorkflowId(workflowId);
		resetChangedOnNotNull();
	}
}
