;configuration should be working without any modification

[DEFAULT]
base=/app/scripts

[scripts]
;control (stop, start, restart) an application
control=control.sh
;backup application
backup=backup.sh
;reset application
reset=reset.sh
;restore application
restore=restore.sh

[backups]
cleanup_cron_expression=0 2 * * *
;backup maximum age in seconds: 90 days = 60 * 60 * 24 * 90 = 7776000 seconds
max_age=7776000
;rollover age in seconds: 7 days = 60 * 60 * 24 * 7 = 604800 seconds
rollover_age=604800
;rollover day (day that will be kept)
rollover_day=Wed
