/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User-submitted credentials
 */
export interface CredentialsDTO { 
    /**
     * User e-mail
     */
    email: string;
    /**
     * Plain-text password
     */
    password?: string;
    /**
     * Special key used to authenticate user. If provided password, token and code must be blank.
     */
    authKey?: string;
}

