/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldModelCriterion } from './field-model-criterion-dto';
import { EnrollmentType } from './enrollment-type-dto';


export interface EnrollmentModel { 
    draft?: boolean;
    system?: boolean;
    type?: EnrollmentType;
    scopesContainerIds?: Set<string>;
    criteria?: Array<FieldModelCriterion>;
}
export namespace EnrollmentModel {
}


