/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventModelDTO { 
    id: string;
    shortname: { [key: string]: string; };
    datasetModelIds: Array<string>;
    formModelIds: Array<string>;
    workflowIds: Array<string>;
    deadline?: number;
    deadlineUnit?: EventModelDTO.DeadlineUnitEnum;
    deadlineReferenceEventModelIds?: Array<string>;
    deadlineAggregationFunction?: EventModelDTO.DeadlineAggregationFunctionEnum;
    interval?: number;
    intervalUnit?: EventModelDTO.IntervalUnitEnum;
    icon?: string;
    number?: number;
}
export namespace EventModelDTO {
    export type DeadlineUnitEnum = 'Nanos' | 'Micros' | 'Millis' | 'Seconds' | 'Minutes' | 'Hours' | 'HalfDays' | 'Days' | 'Weeks' | 'Months' | 'Years' | 'Decades' | 'Centuries' | 'Millennia' | 'Eras' | 'Forever';
    export const DeadlineUnitEnum = {
        NANOS: 'Nanos' as DeadlineUnitEnum,
        MICROS: 'Micros' as DeadlineUnitEnum,
        MILLIS: 'Millis' as DeadlineUnitEnum,
        SECONDS: 'Seconds' as DeadlineUnitEnum,
        MINUTES: 'Minutes' as DeadlineUnitEnum,
        HOURS: 'Hours' as DeadlineUnitEnum,
        HALF_DAYS: 'HalfDays' as DeadlineUnitEnum,
        DAYS: 'Days' as DeadlineUnitEnum,
        WEEKS: 'Weeks' as DeadlineUnitEnum,
        MONTHS: 'Months' as DeadlineUnitEnum,
        YEARS: 'Years' as DeadlineUnitEnum,
        DECADES: 'Decades' as DeadlineUnitEnum,
        CENTURIES: 'Centuries' as DeadlineUnitEnum,
        MILLENNIA: 'Millennia' as DeadlineUnitEnum,
        ERAS: 'Eras' as DeadlineUnitEnum,
        FOREVER: 'Forever' as DeadlineUnitEnum
    };
    export type DeadlineAggregationFunctionEnum = 'MAX' | 'MIN';
    export const DeadlineAggregationFunctionEnum = {
        MAX: 'MAX' as DeadlineAggregationFunctionEnum,
        MIN: 'MIN' as DeadlineAggregationFunctionEnum
    };
    export type IntervalUnitEnum = 'Nanos' | 'Micros' | 'Millis' | 'Seconds' | 'Minutes' | 'Hours' | 'HalfDays' | 'Days' | 'Weeks' | 'Months' | 'Years' | 'Decades' | 'Centuries' | 'Millennia' | 'Eras' | 'Forever';
    export const IntervalUnitEnum = {
        NANOS: 'Nanos' as IntervalUnitEnum,
        MICROS: 'Micros' as IntervalUnitEnum,
        MILLIS: 'Millis' as IntervalUnitEnum,
        SECONDS: 'Seconds' as IntervalUnitEnum,
        MINUTES: 'Minutes' as IntervalUnitEnum,
        HOURS: 'Hours' as IntervalUnitEnum,
        HALF_DAYS: 'HalfDays' as IntervalUnitEnum,
        DAYS: 'Days' as IntervalUnitEnum,
        WEEKS: 'Weeks' as IntervalUnitEnum,
        MONTHS: 'Months' as IntervalUnitEnum,
        YEARS: 'Years' as IntervalUnitEnum,
        DECADES: 'Decades' as IntervalUnitEnum,
        CENTURIES: 'Centuries' as IntervalUnitEnum,
        MILLENNIA: 'Millennia' as IntervalUnitEnum,
        ERAS: 'Eras' as IntervalUnitEnum,
        FOREVER: 'Forever' as IntervalUnitEnum
    };
}


