/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldModelType } from './field-model-type-dto';
import { OperandType } from './operand-type-dto';
import { PossibleValue } from './possible-value-dto';


/**
 * Field model
 */
export interface FieldModel { 
    fieldModelId: string;
    type?: FieldModelType;
    dataType: OperandType;
    datasetModelId: string;
    id: string;
    shortname: { [key: string]: string; };
    longname: { [key: string]: string; };
    description?: { [key: string]: string; };
    /**
     * Possible values of the field, if the field type is a multiple
     */
    possibleValues: Array<PossibleValue>;
    dictionary?: string;
    readOnly: boolean;
    dynamic: boolean;
    order?: number;
    /**
     * Can the field be found in search
     */
    searchable: boolean;
    /**
     * Is the field model included in the exports
     */
    exportable: boolean;
    required: boolean;
    maxLength?: number;
    inlineHelp?: string;
    advancedHelp?: { [key: string]: string; };
    minValue?: number;
    maxValue?: number;
    minYear?: number;
    maxYear?: number;
    maxIntegerDigits?: number;
    maxDecimalDigits?: number;
    allowDateInFuture: boolean;
    withDays: boolean;
    withMonths: boolean;
    withYears: boolean;
    withHours: boolean;
    withMinutes: boolean;
    withSeconds: boolean;
    yearsMandatory: boolean;
    monthsMandatory: boolean;
    daysMandatory: boolean;
    hoursMandatory: boolean;
    minutesMandatory: boolean;
    secondsMandatory: boolean;
}
export namespace FieldModel {
}


