/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * File transmission DTO
 */
export interface FileDTO { 
    pk: number;
    scopePk?: number;
    eventPk?: number;
    datasetPk?: number;
    fieldPk?: number;
    /**
     * File name
     */
    name: string;
    /**
     * File checksum
     */
    checksum: string;
    /**
     * Concatenation of the file name, its checksum encoded in Base32 and file extension. To be used as the file field value.
     */
    uniqueName: string;
}

