/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatasetModelDTO } from './dataset-model-dto';
import { LayoutLineDTO } from './layout-line-dto';


export interface LayoutDTO { 
    scopePk: number;
    eventPk?: number;
    id: string;
    formModelId: string;
    description?: { [key: string]: string; };
    type: LayoutDTO.TypeEnum;
    datasetModel: DatasetModelDTO;
    defaultSortFieldModelId?: string;
    contribution: boolean;
    lines: Array<LayoutLineDTO>;
    textBefore?: { [key: string]: string; };
    textAfter?: { [key: string]: string; };
    cssCode?: string;
    htmlClass?: string;
    jsCode?: string;
}
export namespace LayoutDTO {
    export type TypeEnum = 'SINGLE' | 'MULTIPLE';
    export const TypeEnum = {
        SINGLE: 'SINGLE' as TypeEnum,
        MULTIPLE: 'MULTIPLE' as TypeEnum
    };
}


