/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ColumnHeader } from './column-header-dto';
import { LayoutLine } from './layout-line-dto';
import { LayoutType } from './layout-type-dto';
import { DatasetModel } from './dataset-model-dto';


export interface Layout { 
    formLayoutId: string;
    scopePk: number;
    eventPk?: number;
    id: string;
    formModelId: string;
    description?: { [key: string]: string; };
    type: LayoutType;
    datasetModel: DatasetModel;
    defaultSortFieldModelId?: string;
    contribution: boolean;
    columns: Array<ColumnHeader>;
    lines: Array<LayoutLine>;
    textBefore?: { [key: string]: string; };
    textAfter?: { [key: string]: string; };
    cssCode?: string;
}
export namespace Layout {
}


