/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailAttachmentDTO } from './mail-attachment-dto';


export interface MailDTO { 
    recipients: Set<string>;
    subject: string;
    textBody: string;
    pk: number;
    creationTime: Date;
    lastUpdateTime: Date;
    origin?: MailDTO.OriginEnum;
    status: MailDTO.StatusEnum;
    error?: string;
    sentTime?: Date;
    intent?: string;
    sender: string;
    htmlBody?: string;
    attempts: number;
    replyTo?: string;
    attachmentsDTO: Array<MailAttachmentDTO>;
}
export namespace MailDTO {
    export type OriginEnum = 'UNDEFINED' | 'RULE' | 'TASK' | 'USER' | 'SYSTEM' | 'ERROR';
    export const OriginEnum = {
        UNDEFINED: 'UNDEFINED' as OriginEnum,
        RULE: 'RULE' as OriginEnum,
        TASK: 'TASK' as OriginEnum,
        USER: 'USER' as OriginEnum,
        SYSTEM: 'SYSTEM' as OriginEnum,
        ERROR: 'ERROR' as OriginEnum
    };
    export type StatusEnum = 'PENDING' | 'SENT' | 'SIMULATED' | 'CANCELED' | 'FAILED';
    export const StatusEnum = {
        PENDING: 'PENDING' as StatusEnum,
        SENT: 'SENT' as StatusEnum,
        SIMULATED: 'SIMULATED' as StatusEnum,
        CANCELED: 'CANCELED' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
}


