/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfileDTO { 
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    features: Set<string>;
    profilesRight: { [key: string]: Set<string>; };
}
export namespace ProfileDTO {
    export type ProfilesRightEnum = 'READ' | 'WRITE';
    export const ProfilesRightEnum = {
        READ: 'READ' as ProfilesRightEnum,
        WRITE: 'WRITE' as ProfilesRightEnum
    };
}


