/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LanguageDTO } from './language-dto';
import { ScopeModelDTO } from './scope-model-dto';
import { MenuDTO } from './menu-dto';


export interface PublicStudyDTO { 
    id: string;
    shortname: { [key: string]: string; };
    color: string;
    url: string;
    homePage: MenuDTO;
    eproEnabled: boolean;
    introductionText?: string;
    copyright?: string;
    activatedLanguages: Array<LanguageDTO>;
    defaultLanguage: LanguageDTO;
    environment: PublicStudyDTO.EnvironmentEnum;
    leafScopeModel: ScopeModelDTO;
}
export namespace PublicStudyDTO {
    export type EnvironmentEnum = 'PROD' | 'VAL' | 'DEV';
    export const EnvironmentEnum = {
        PROD: 'PROD' as EnvironmentEnum,
        VAL: 'VAL' as EnvironmentEnum,
        DEV: 'DEV' as EnvironmentEnum
    };
}


