/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Language } from './language-dto';
import { ScopeModel } from './scope-model-dto';
import { Environment } from './environment-dto';
import { Menu } from './menu-dto';
import { Profile } from './profile-dto';


export interface PublicStudy { 
    projectId: string;
    id: string;
    shortname: { [key: string]: string; };
    color: string;
    logo?: string;
    url: string;
    homePage: Menu;
    eproEnabled: boolean;
    introductionText?: string;
    copyright?: string;
    activatedLanguages: Array<Language>;
    defaultLanguage: Language;
    environment: Environment;
    leafScopeModel: ScopeModel;
    eproProfile?: Profile;
}
export namespace PublicStudy {
}


