/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceCategoryDTO } from './resource-category-dto';


export interface ResourceDTO { 
    title: string;
    description?: string;
    categoryId: string;
    scopePk: number;
    publicResource: boolean;
    pk: number;
    creationTime: Date;
    lastUpdateTime: Date;
    category: ResourceCategoryDTO;
    canBeManaged: boolean;
    scopeShortname: string;
    userPk: number;
    userEmail: string;
    userName: string;
    removed: boolean;
    filename?: string;
}

