/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScopeMiniDTO } from './scope-mini-dto';


/**
 * Represents the parent-child relation between two scopes
 */
export interface ScopeRelationDTO { 
    _default: boolean;
    pk: number;
    startDate: Date;
    stopDate: Date;
    scope: ScopeMiniDTO;
    parent: ScopeMiniDTO;
}

