/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrollmentTarget } from './enrollment-target-dto';
import { EnrollmentModel } from './enrollment-model-dto';
import { SubscriptionRestriction } from './subscription-restriction-dto';
import { EventConfigurationHook } from './event-configuration-hook-dto';


export interface ScopeData {
    description?: { [key: string]: string; };
    enrollmentModel?: EnrollmentModel;
    enrollmentStart?: Date;
    enrollmentStop?: Date;
    enrollmentTargets?: Array<EnrollmentTarget>;
    eventConfigurationHooks?: Array<EventConfigurationHook>;
    subscriptionRestrictions?: Array<SubscriptionRestriction>;
}

