/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatsInStateDTO { 
    total: number;
    cumulative: number;
    percent: number;
    percentCumulative: number;
    leafScopes: Set<number>;
    percentFormatted?: string;
    percentCumulativeFormatted?: string;
}

