/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionRestriction { 
    model?: string;
    scopeIds?: Array<string>;
    attribute?: SubscriptionRestriction.AttributeEnum;
    values?: Array<string>;
}
export namespace SubscriptionRestriction {
    export type AttributeEnum = 'Language' | 'Country' | 'Gender' | 'Birthdate' | 'Phone' | 'Mobile phone';
    export const AttributeEnum = {
        LANGUAGE: 'Language' as AttributeEnum,
        COUNTRY: 'Country' as AttributeEnum,
        GENDER: 'Gender' as AttributeEnum,
        BIRTHDATE: 'Birthdate' as AttributeEnum,
        PHONE: 'Phone' as AttributeEnum,
        MOBILE_PHONE: 'Mobile phone' as AttributeEnum
    };
}


