/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryColumn } from './summary-column-dto';
import { SummaryRow } from './summary-row-dto';


export interface Summary { 
    workflowSummaryId: string;
    id: string;
    title: { [key: string]: string; };
    leafScopeModelId: string;
    columns: Array<SummaryColumn>;
    rows: Array<SummaryRow>;
}

