/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimelineGraphDataPeriod } from './timeline-graph-data-period';


/**
 * Timeline graph data
 */
export interface TimelineGraphDataDTO { 
    id: string;
    shortname: { [key: string]: string; };
    longname: { [key: string]: string; };
    description?: { [key: string]: string; };
    scopeModelId: string;
    studyStartEventModelId?: string;
    studyStopEventModelId?: string;
    studyPeriodIsDefault?: boolean;
    width?: number;
    height?: number;
    legendWidth?: number;
    scrollerHeight?: number;
    showScroller: boolean;
    footNote?: { [key: string]: string; };
    periods: Array<TimelineGraphDataPeriod>;
}

