/**
 * KV API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: DEV-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './user-dto';
import { PrivacyPolicyDTO } from './privacy-policy-dto';


/**
 * An object wrapping a user and the privacy policies presented to them
 */
export interface UserAndPrivacyPoliciesDTO { 
    user: UserDTO;
    /**
     * Privacy policies presented to the user
     */
    policies: Set<PrivacyPolicyDTO>;
}

