#!/usr/bin/env bash

###DO NOT EDIT THIS FILE, USE CONFIG.SH###

#retrieve parameters
DATABASE_NAME=$1
DUMP_PATH=$2

#fail if a variable is referenced before being set or if a command fails
set -u -e

#check parameters
if [[ -z $DATABASE_NAME ]] || [[ -z $DUMP_PATH ]]
then
	echo "Usage: database-name dump-path"
	exit 1
fi

if [[ -f "$DUMP_PATH" ]]
then
	echo "$DUMP_PATH already exists"
	exit 1
fi

#shellcheck source=check.sh
source "$(dirname "${BASH_SOURCE[0]}")/check.sh"

mariadb_connection_arguments=("-hlocalhost" "-u$DATABASE_USER" "-p$DATABASE_PASSWORD")

#retrieve tables to dump
#the goal is to exclude the views from the dump (they will re-created automatically anyway)
#this is because mariadb-dump hard-codes the name of the database in the SQL code of the views in the resulting file
#when views are in the dump, it's not possible to import the dump in a database with a different name
mariadb_tables_arguments=("${mariadb_connection_arguments[@]}")
mariadb_tables_arguments+=("-s" "-r" "-N" "-e")
mariadb_tables_arguments+=("select table_name from information_schema.tables where table_schema = '$DATABASE_NAME' and table_type != 'VIEW'")
mapfile -t tables < <(mariadb "${mariadb_tables_arguments[@]}")

#build MariaDB dump arguments
mariadb_dump_arguments=("${mariadb_connection_arguments[@]}")
#for information on the different mariadb-dump parameters, check this page https://mariadb.com/kb/en/mariadb-dump/
mariadb_dump_arguments+=("--single-transaction" "--quick" "--hex-blob" "--order-by-primary" "--triggers" "--add-drop-trigger" "--routines")
mariadb_dump_arguments+=("$DATABASE_NAME")
mariadb_dump_arguments+=("${tables[@]}")

#dump database
mariadb-dump "${mariadb_dump_arguments[@]}" | gzip > "$DUMP_PATH"
