all:
  hosts:
    test.rodano.ch:
      ansible_python_interpreter: /usr/bin/python3.13
      ansible_ssh_user: debian
      study_git_url: https://github.com/rodano/study-test.git
      study_git_reference: main
      rodano_git_reference: dev
      server_name: test.rodano.ch
      server_email: info@rodano.ch
      manager_magic_token: mylongmagictoken
