all:
  hosts:
    test.rodano.ch:
      ansible_python_interpreter: /usr/bin/python3.13
      ansible_ssh_user: debian
      study_git_url: https://github.com/rodano/study-test.git
      study_git_reference: main
      server_name: test.rodano.ch
      server_email: info@rodano.ch
      rodano_environment:
        TAG: "{{ rodano_tag | default('dev') }}"
        MANAGER_MAGIC_TOKEN: mylongmagictoken
