/*
 * This file is generated by jOOQ.
 */
package ch.rodano.core.model.jooq;


import ch.rodano.core.model.jooq.tables.AuditAction;
import ch.rodano.core.model.jooq.tables.Chart;
import ch.rodano.core.model.jooq.tables.ChartCategory;
import ch.rodano.core.model.jooq.tables.ChartColor;
import ch.rodano.core.model.jooq.tables.ChartState;
import ch.rodano.core.model.jooq.tables.Dataset;
import ch.rodano.core.model.jooq.tables.DatasetAudit;
import ch.rodano.core.model.jooq.tables.Event;
import ch.rodano.core.model.jooq.tables.EventAudit;
import ch.rodano.core.model.jooq.tables.Field;
import ch.rodano.core.model.jooq.tables.FieldAudit;
import ch.rodano.core.model.jooq.tables.File;
import ch.rodano.core.model.jooq.tables.Form;
import ch.rodano.core.model.jooq.tables.FormAudit;
import ch.rodano.core.model.jooq.tables.Mail;
import ch.rodano.core.model.jooq.tables.MailAttachment;
import ch.rodano.core.model.jooq.tables.Payment;
import ch.rodano.core.model.jooq.tables.PaymentBatch;
import ch.rodano.core.model.jooq.tables.PaymentTarget;
import ch.rodano.core.model.jooq.tables.Resource;
import ch.rodano.core.model.jooq.tables.Robot;
import ch.rodano.core.model.jooq.tables.RobotAudit;
import ch.rodano.core.model.jooq.tables.Role;
import ch.rodano.core.model.jooq.tables.RoleAudit;
import ch.rodano.core.model.jooq.tables.Scope;
import ch.rodano.core.model.jooq.tables.ScopeAncestor;
import ch.rodano.core.model.jooq.tables.ScopeAudit;
import ch.rodano.core.model.jooq.tables.ScopeRelation;
import ch.rodano.core.model.jooq.tables.User;
import ch.rodano.core.model.jooq.tables.UserAudit;
import ch.rodano.core.model.jooq.tables.UserSession;
import ch.rodano.core.model.jooq.tables.WorkflowStatus;
import ch.rodano.core.model.jooq.tables.WorkflowStatusAudit;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

	/**
	 * The table <code>audit_action</code>.
	 */
	public static final AuditAction AUDIT_ACTION = AuditAction.AUDIT_ACTION;

	/**
	 * The table <code>chart</code>.
	 */
	public static final Chart CHART = Chart.CHART;

	/**
	 * The table <code>chart_category</code>.
	 */
	public static final ChartCategory CHART_CATEGORY = ChartCategory.CHART_CATEGORY;

	/**
	 * The table <code>chart_color</code>.
	 */
	public static final ChartColor CHART_COLOR = ChartColor.CHART_COLOR;

	/**
	 * The table <code>chart_state</code>.
	 */
	public static final ChartState CHART_STATE = ChartState.CHART_STATE;

	/**
	 * The table <code>dataset</code>.
	 */
	public static final Dataset DATASET = Dataset.DATASET;

	/**
	 * The table <code>dataset_audit</code>.
	 */
	public static final DatasetAudit DATASET_AUDIT = DatasetAudit.DATASET_AUDIT;

	/**
	 * The table <code>event</code>.
	 */
	public static final Event EVENT = Event.EVENT;

	/**
	 * The table <code>event_audit</code>.
	 */
	public static final EventAudit EVENT_AUDIT = EventAudit.EVENT_AUDIT;

	/**
	 * The table <code>field</code>.
	 */
	public static final Field FIELD = Field.FIELD;

	/**
	 * The table <code>field_audit</code>.
	 */
	public static final FieldAudit FIELD_AUDIT = FieldAudit.FIELD_AUDIT;

	/**
	 * The table <code>file</code>.
	 */
	public static final File FILE = File.FILE;

	/**
	 * The table <code>form</code>.
	 */
	public static final Form FORM = Form.FORM;

	/**
	 * The table <code>form_audit</code>.
	 */
	public static final FormAudit FORM_AUDIT = FormAudit.FORM_AUDIT;

	/**
	 * The table <code>mail</code>.
	 */
	public static final Mail MAIL = Mail.MAIL;

	/**
	 * The table <code>mail_attachment</code>.
	 */
	public static final MailAttachment MAIL_ATTACHMENT = MailAttachment.MAIL_ATTACHMENT;

	/**
	 * The table <code>payment</code>.
	 */
	public static final Payment PAYMENT = Payment.PAYMENT;

	/**
	 * The table <code>payment_batch</code>.
	 */
	public static final PaymentBatch PAYMENT_BATCH = PaymentBatch.PAYMENT_BATCH;

	/**
	 * The table <code>payment_target</code>.
	 */
	public static final PaymentTarget PAYMENT_TARGET = PaymentTarget.PAYMENT_TARGET;

	/**
	 * The table <code>resource</code>.
	 */
	public static final Resource RESOURCE = Resource.RESOURCE;

	/**
	 * The table <code>robot</code>.
	 */
	public static final Robot ROBOT = Robot.ROBOT;

	/**
	 * The table <code>robot_audit</code>.
	 */
	public static final RobotAudit ROBOT_AUDIT = RobotAudit.ROBOT_AUDIT;

	/**
	 * The table <code>role</code>.
	 */
	public static final Role ROLE = Role.ROLE;

	/**
	 * The table <code>role_audit</code>.
	 */
	public static final RoleAudit ROLE_AUDIT = RoleAudit.ROLE_AUDIT;

	/**
	 * The table <code>scope</code>.
	 */
	public static final Scope SCOPE = Scope.SCOPE;

	/**
	 * The table <code>scope_ancestor</code>.
	 */
	public static final ScopeAncestor SCOPE_ANCESTOR = ScopeAncestor.SCOPE_ANCESTOR;

	/**
	 * The table <code>scope_audit</code>.
	 */
	public static final ScopeAudit SCOPE_AUDIT = ScopeAudit.SCOPE_AUDIT;

	/**
	 * The table <code>scope_relation</code>.
	 */
	public static final ScopeRelation SCOPE_RELATION = ScopeRelation.SCOPE_RELATION;

	/**
	 * The table <code>user</code>.
	 */
	public static final User USER = User.USER;

	/**
	 * The table <code>user_audit</code>.
	 */
	public static final UserAudit USER_AUDIT = UserAudit.USER_AUDIT;

	/**
	 * The table <code>user_session</code>.
	 */
	public static final UserSession USER_SESSION = UserSession.USER_SESSION;

	/**
	 * The table <code>workflow_status</code>.
	 */
	public static final WorkflowStatus WORKFLOW_STATUS = WorkflowStatus.WORKFLOW_STATUS;

	/**
	 * The table <code>workflow_status_audit</code>.
	 */
	public static final WorkflowStatusAudit WORKFLOW_STATUS_AUDIT = WorkflowStatusAudit.WORKFLOW_STATUS_AUDIT;
}
