/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ChronoUnit = 'Nanos' | 'Micros' | 'Millis' | 'Seconds' | 'Minutes' | 'Hours' | 'HalfDays' | 'Days' | 'Weeks' | 'Months' | 'Years' | 'Decades' | 'Centuries' | 'Millennia' | 'Eras' | 'Forever';

export const ChronoUnit = {
    NANOS: 'Nanos' as ChronoUnit,
    MICROS: 'Micros' as ChronoUnit,
    MILLIS: 'Millis' as ChronoUnit,
    SECONDS: 'Seconds' as ChronoUnit,
    MINUTES: 'Minutes' as ChronoUnit,
    HOURS: 'Hours' as ChronoUnit,
    HALF_DAYS: 'HalfDays' as ChronoUnit,
    DAYS: 'Days' as ChronoUnit,
    WEEKS: 'Weeks' as ChronoUnit,
    MONTHS: 'Months' as ChronoUnit,
    YEARS: 'Years' as ChronoUnit,
    DECADES: 'Decades' as ChronoUnit,
    CENTURIES: 'Centuries' as ChronoUnit,
    MILLENNIA: 'Millennia' as ChronoUnit,
    ERAS: 'Eras' as ChronoUnit,
    FOREVER: 'Forever' as ChronoUnit
};

