/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CMSSectionDTO } from './cms-section-dto';


/**
 * A layout contains of a list of sections
 */
export interface CMSLayoutDTO { 
    /**
     * Layout sections
     */
    sections: Array<CMSSectionDTO>;
}

