/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of inconsistency: MISSING_IN_DATABASE or MISSING_IN_CONFIGURATION
 */
export type ConfigurationInconsistencyType = 'MISSING_IN_DATABASE' | 'MISSING_IN_CONFIGURATION';

export const ConfigurationInconsistencyType = {
    MISSING_IN_DATABASE: 'MISSING_IN_DATABASE' as ConfigurationInconsistencyType,
    MISSING_IN_CONFIGURATION: 'MISSING_IN_CONFIGURATION' as ConfigurationInconsistencyType
};

