/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FIXABLE: issue detected but not fixed (dry run); FIXED: issue has been fixed; NOT_FIXABLE: issue cannot be automatically fixed
 */
export type DatabaseIssueStatus = 'FIXABLE' | 'FIXED' | 'NOT_FIXABLE';

export const DatabaseIssueStatus = {
    FIXABLE: 'FIXABLE' as DatabaseIssueStatus,
    FIXED: 'FIXED' as DatabaseIssueStatus,
    NOT_FIXABLE: 'NOT_FIXABLE' as DatabaseIssueStatus
};

