/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseIssueStatus } from './database-issue-status';
import { DatabaseIssueEntity } from './database-issue-entity';
import { DatabaseIssueType } from './database-issue-type';


/**
 * An issue detected during a database consistency check
 */
export interface DatabaseIssue { 
    entity: DatabaseIssueEntity;
    /**
     * Model id of the affected entity
     */
    modelId: string;
    /**
     * Primary key of the affected entity
     */
    pk: number;
    type: DatabaseIssueType;
    /**
     * Description of the issue
     */
    error: string;
    status: DatabaseIssueStatus;
}
export namespace DatabaseIssue {
}


