/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Scheme for demo users
 */
export interface DemoUserSchemeDTO { 
    /**
     * Base e-mail
     */
    baseEmail: string;
    /**
     * Password of the users
     */
    password: string;
}

