/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EnrollmentType = 'AUTOMATIC' | 'MANUAL';

export const EnrollmentType = {
    AUTOMATIC: 'AUTOMATIC' as EnrollmentType,
    MANUAL: 'MANUAL' as EnrollmentType
};

