/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Event groups
 */
export interface EventGroup { 
    id: string;
    shortname: { [key: string]: string; };
}

