/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HighChartSerie } from './high-chart-serie';


export interface HighGraph { 
    series?: Array<HighChartSerie>;
    count?: { [key: string]: number; };
    type?: string;
    min?: { [key: string]: number; };
    max?: { [key: string]: number; };
    statisticsUsePercentile?: boolean;
    defaultTitle?: string;
    legendXLabel?: string;
    legendYLabel?: string;
    legendXColor?: string;
    percentile95?: { [key: string]: number; };
    legendYColor?: string;
    displayStatistics?: boolean;
    title?: string;
    stacked?: boolean;
    inverted?: boolean;
    percentile5?: { [key: string]: number; };
    median?: { [key: string]: number; };
    showMarkers?: boolean;
    inPercent?: boolean;
    mean?: { [key: string]: number; };
    colors?: Array<string>;
    sd?: { [key: string]: number; };
}

