/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Kind = 'INCLUDED' | 'EXCLUDED' | 'ENROLLMENT';

export const Kind = {
    INCLUDED: 'INCLUDED' as Kind,
    EXCLUDED: 'EXCLUDED' as Kind,
    ENROLLMENT: 'ENROLLMENT' as Kind
};

