/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines a report that is presented to users
 */
export interface Report { 
    /**
     * Report UUID
     */
    reportId: string;
    /**
     * Report ID
     */
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    workflowId: string;
    datasetModelId: string;
    /**
     * Field models affected by the report
     */
    fieldModelIds: Array<string>;
}

