/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordDTO { 
    /**
     * Reset code
     */
    resetCode: string;
    /**
     * New password
     */
    newPassword: string;
}

