/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceSubmissionDTO { 
    title: string;
    description?: string;
    categoryId: string;
    scopePk: number;
    publicResource: boolean;
}

