/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResourceCategoryDTO { 
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    color?: string;
    icon?: string;
}

