/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RoleStatus = 'PENDING' | 'ENABLED' | 'DISABLED';

export const RoleStatus = {
    PENDING: 'PENDING' as RoleStatus,
    ENABLED: 'ENABLED' as RoleStatus,
    DISABLED: 'DISABLED' as RoleStatus
};

