/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleAction } from './rule-action';
import { RuleConstraint } from './rule-constraint';


export interface Rule { 
    ruleId?: string;
    ruleType?: string;
    description?: string;
    message?: { [key: string]: string; };
    tags?: Array<string>;
    constraint?: RuleConstraint;
    actions?: Array<RuleAction>;
}

