/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleCriterion } from './rule-criterion';


export interface RuleCondition { 
    ruleConditionId?: string;
    id?: string;
    criterion?: RuleCriterion;
    inverse?: boolean;
    dependency?: boolean;
    breakType?: string;
    mode?: string;
}

