/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScopeTinyDTO { 
    pk: number;
    modelId: string;
    code: string;
    shortname: string;
    longname: string;
}

