/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatsInStateDTO { 
    total: number;
    cumulative: number;
    percent: number;
    percentCumulative: number;
    leafScopes: Set<number>;
    percentCumulativeFormatted?: string;
    percentFormatted?: string;
}

