/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimelineGraphSectionReference } from './timeline-graph-section-reference';


export interface TimelineGraphSection { 
    graphSectionId: string;
    id: string;
    type: string;
    timelineGraphId: string;
    datasetModelId?: string;
    dateFieldId?: string;
    endDateFieldId?: string;
    labelFieldId?: string;
    valueFieldId?: string;
    hideExpectedEvent?: boolean;
    hideDoneEvent?: boolean;
    useScopePaths?: boolean;
    unit?: string;
    color?: string;
    strokeColor?: string;
    opacity?: number;
    dashed?: boolean;
    mark?: string;
    positionStart?: number;
    positionStop?: number;
    scaleMin?: number;
    scaleMax?: number;
    scaleDecimal?: number;
    scaleMarkInterval?: number;
    scaleLabelInterval?: number;
    scalePosition?: string;
    hiddenLegend?: boolean;
    hidden?: boolean;
    label: { [key: string]: string; };
    tooltip?: { [key: string]: string; };
    eventModelIds?: Array<string>;
    metaFieldIds?: Array<string>;
    /**
     * Section References
     */
    references: Array<TimelineGraphSectionReference>;
}

