/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectStatus } from './project-status';


export interface UpdateProjectStatusRequest { 
    status?: ProjectStatus;
}
export namespace UpdateProjectStatusRequest {
}


