/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Update a user
 */
export interface UserUpdate { 
    /**
     * Name
     */
    name: string;
    /**
     * Language ID
     */
    languageId?: string;
    /**
     * Phone number
     */
    phone?: string;
}

