/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivacyPolicyDTO } from './privacy-policy-dto';


export interface UserPrivacyPoliciesDTO { 
    email: string;
    policies: Array<PrivacyPolicyDTO>;
}

