/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowWidgetColumnType } from './workflow-widget-column-type';


/**
 * Workflow widget column configuration
 */
export interface WorkflowWidgetColumnDTO { 
    /**
     * Column ID
     */
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    /**
     * Type of column
     */
    type: WorkflowWidgetColumnType;
    /**
     * Width of the column in px
     */
    width: number;
}
export namespace WorkflowWidgetColumnDTO {
}


