/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowableEntity } from './workflowable-entity';
import { WorkflowWidgetColumn } from './workflow-widget-column';


/**
 * Widget that shows workflows based on specified criteria
 */
export interface WorkflowWidget { 
    /**
     * Widget ID
     */
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    /**
     * Are the workflows related to the expected events filtered out from the widget?
     */
    filterExpectedEvents: boolean;
    workflowEntity: WorkflowableEntity;
    /**
     * Widget columns configuration
     */
    columns: Array<WorkflowWidgetColumn>;
}
export namespace WorkflowWidget {
}


