/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WorkflowableEntity = 'SCOPE' | 'EVENT' | 'FORM' | 'FIELD';

export const WorkflowableEntity = {
    SCOPE: 'SCOPE' as WorkflowableEntity,
    EVENT: 'EVENT' as WorkflowableEntity,
    FORM: 'FORM' as WorkflowableEntity,
    FIELD: 'FIELD' as WorkflowableEntity
};

