/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkflowUpdateDTO { 
    /**
     * Workflow id when creating a new workflow
     */
    workflowId: string;
    /**
     * Action id
     */
    actionId?: string;
    /**
     * Rationale
     */
    rationale?: string;
    /**
     * User email for authentication
     */
    email?: string;
    /**
     * User password for authentication
     */
    password?: string;
}

