/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowActionDTO } from './workflow-action-dto';
import { WorkflowStateDTO } from './workflow-state-dto';


/**
 * The workflow model
 */
export interface WorkflowDTO { 
    /**
     * The unique ID of the workflow
     */
    id: string;
    shortname: { [key: string]: string; };
    longname?: { [key: string]: string; };
    description?: { [key: string]: string; };
    /**
     * Is the workflow an aggregate workflow?
     */
    aggregator: boolean;
    /**
     * Aggregated workflow Id
     */
    aggregatedWorkflowId?: string;
    /**
     * Is the workflow mandatory?
     */
    mandatory: boolean;
    actionId?: string;
    /**
     * Message attached to the workflow
     */
    message: { [key: string]: string; };
    icon?: string;
    /**
     * Possible states of the workflow
     */
    states: Array<WorkflowStateDTO>;
    /**
     * Possible actions that can be performed on the workflow
     */
    actions: Array<WorkflowActionDTO>;
}

