/**
 * Rodano API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowState } from './workflow-state';
import { Workflow } from './workflow';


export interface WorkflowStatus { 
    pk: number;
    /**
     * The workflow ID
     */
    workflowId: string;
    /**
     * The workflow status ID
     */
    statusId: string;
    /**
     * User message that was attached to the latest status change
     */
    triggerMessage: string;
    workflow: Workflow;
    state: WorkflowState;
    /**
     * Date of the WorkflowStatus
     */
    date: Date;
    orderBy?: number;
    /**
     * The ID of the action used to create the workflow
     */
    creationActionId?: string;
    /**
     * Scope reference of the WorkflowStatus
     */
    scopeFk: number;
    /**
     * Code of the scope to which WorkflowStatus is attached to
     */
    scopeCode: string;
    /**
     * Shortname of the scope to which WorkflowStatus is attached to
     */
    scopeShortname: string;
    /**
     * Event reference of the WorkflowStatus
     */
    eventFk?: number;
    /**
     * Shortname of the event to which WorkflowStatus is attached to
     */
    eventShortname?: string;
    /**
     * Date of the event to which WorkflowStatus is attached to
     */
    eventDate?: Date;
    /**
     * Field reference of the WorkflowStatus
     */
    fieldFk?: number;
    /**
     * Shortname of the field to which WorkflowStatus is attached to
     */
    fieldShortname?: string;
}

