name: Build and publish Docker images

permissions:
  contents: read
  packages: write
  id-token: write

on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  publish-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the project
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve the metadata for the backend image
        id: backend-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/rodano/backend

      - name: Publish the backend image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          tags: ${{steps.backend-meta.outputs.tags}}
          labels: ${{steps.backend-meta.outputs.labels}}

      - name: Retrieve the metadata for the plugins compiler image
        id: plugins-compiler-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/rodano/plugins-compiler

      - name: Publish the plugins compiler image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          target: plugins-compiler
          tags: ${{steps.plugins-compiler-meta.outputs.tags}}
          labels: ${{steps.plugins-compiler-meta.outputs.labels}}

  publish-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the project
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve the metadata for the frontend image
        id: frontend-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/rodano/frontend

      - name: Publish the frontend image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: frontends
          tags: ${{steps.frontend-meta.outputs.tags}}
          labels: ${{steps.frontend-meta.outputs.labels}}
